// ==================== БАЗА ПРЕДЛОЖЕНИЙ ДЛЯ ДИКТАНТА (600 ФРАЗ) ====================
const phrasesDB = [
    // ==================== УРОВЕНЬ 1 ⭐: ПРИВЕТСТВИЯ, ВЕЖЛИВОСТЬ, БАЗОВЫЕ ФРАЗЫ (120 фраз) ====================
    // --- Приветствия (20) ---
    { chinese: "你好", pinyin: "nǐ hǎo", russian: "Привет", level: 1, words: ["你", "好"] },
    { chinese: "你们好", pinyin: "nǐmen hǎo", russian: "Всем привет", level: 1, words: ["你", "们", "好"] },
    { chinese: "您好", pinyin: "nín hǎo", russian: "Здравствуйте", level: 1, words: ["您", "好"] },
    { chinese: "大家好", pinyin: "dàjiā hǎo", russian: "Всем здравствуйте", level: 1, words: ["大", "家", "好"] },
    { chinese: "早上好", pinyin: "zǎoshang hǎo", russian: "Доброе утро", level: 1, words: ["早", "上", "好"] },
    { chinese: "早安", pinyin: "zǎo ān", russian: "Доброе утро (короче)", level: 1, words: ["早", "安"] },
    { chinese: "下午好", pinyin: "xiàwǔ hǎo", russian: "Добрый день", level: 1, words: ["下", "午", "好"] },
    { chinese: "晚上好", pinyin: "wǎnshang hǎo", russian: "Добрый вечер", level: 1, words: ["晚", "上", "好"] },
    { chinese: "晚安", pinyin: "wǎn'ān", russian: "Спокойной ночи", level: 1, words: ["晚", "安"] },
    { chinese: "再见", pinyin: "zài jiàn", russian: "До свидания", level: 1, words: ["再", "见"] },
    { chinese: "拜拜", pinyin: "bài bài", russian: "Пока", level: 1, words: ["拜", "拜"] },
    { chinese: "明天见", pinyin: "míngtiān jiàn", russian: "Увидимся завтра", level: 1, words: ["明", "天", "见"] },
    { chinese: "回头见", pinyin: "huítóu jiàn", russian: "Увидимся позже", level: 1, words: ["回", "头", "见"] },
    { chinese: "一会儿见", pinyin: "yíhuìr jiàn", russian: "Скоро увидимся", level: 1, words: ["一", "会", "儿", "见"] },
    { chinese: "下次见", pinyin: "xià cì jiàn", russian: "Увидимся в следующий раз", level: 1, words: ["下", "次", "见"] },
    { chinese: "你好吗", pinyin: "nǐ hǎo ma", russian: "Как дела?", level: 1, words: ["你", "好", "吗"] },
    { chinese: "最近怎么样", pinyin: "zuìjìn zěnmeyàng", russian: "Как дела в последнее время?", level: 1, words: ["最", "近", "怎", "么", "样"] },
    { chinese: "一切都好吗", pinyin: "yíqiè dōu hǎo ma", russian: "Всё хорошо?", level: 1, words: ["一", "切", "都", "好", "吗"] },
    { chinese: "好久不见", pinyin: "hǎojiǔ bú jiàn", russian: "Давно не виделись", level: 1, words: ["好", "久", "不", "见"] },
    { chinese: "很高兴见到你", pinyin: "hěn gāoxìng jiàndào nǐ", russian: "Рад тебя видеть", level: 1, words: ["很", "高", "兴", "见", "到", "你"] },

    // --- Вежливость и ответы (25) ---
    { chinese: "谢谢", pinyin: "xiè xie", russian: "Спасибо", level: 1, words: ["谢", "谢"] },
    { chinese: "多谢", pinyin: "duō xiè", russian: "Большое спасибо", level: 1, words: ["多", "谢"] },
    { chinese: "非常感谢", pinyin: "fēicháng gǎnxiè", russian: "Огромное спасибо", level: 1, words: ["非", "常", "感", "谢"] },
    { chinese: "谢谢你", pinyin: "xièxie nǐ", russian: "Спасибо тебе", level: 1, words: ["谢", "谢", "你"] },
    { chinese: "谢谢您", pinyin: "xièxie nín", russian: "Спасибо Вам", level: 1, words: ["谢", "谢", "您"] },
    { chinese: "不客气", pinyin: "bú kèqi", russian: "Пожалуйста (ответ)", level: 1, words: ["不", "客", "气"] },
    { chinese: "不用谢", pinyin: "búyòng xiè", russian: "Не за что", level: 1, words: ["不", "用", "谢"] },
    { chinese: "没关系", pinyin: "méi guān xi", russian: "Ничего страшного", level: 1, words: ["没", "关", "系"] },
    { chinese: "没事", pinyin: "méi shì", russian: "Ничего / Всё в порядке", level: 1, words: ["没", "事"] },
    { chinese: "没问题", pinyin: "méi wèntí", russian: "Без проблем", level: 1, words: ["没", "问", "题"] },
    { chinese: "对不起", pinyin: "duì bu qǐ", russian: "Извините", level: 1, words: ["对", "不", "起"] },
    { chinese: "不好意思", pinyin: "bù hǎoyìsi", russian: "Извините (вежл.)", level: 1, words: ["不", "好", "意", "思"] },
    { chinese: "抱歉", pinyin: "bàoqiàn", russian: "Прошу прощения", level: 1, words: ["抱", "歉"] },
    { chinese: "请原谅", pinyin: "qǐng yuánliàng", russian: "Простите пожалуйста", level: 1, words: ["请", "原", "谅"] },
    { chinese: "请进", pinyin: "qǐng jìn", russian: "Входите, пожалуйста", level: 1, words: ["请", "进"] },
    { chinese: "请坐", pinyin: "qǐng zuò", russian: "Садитесь, пожалуйста", level: 1, words: ["请", "坐"] },
    { chinese: "请等一下", pinyin: "qǐng děng yíxià", russian: "Подождите, пожалуйста", level: 1, words: ["请", "等", "一", "下"] },
    { chinese: "请帮我", pinyin: "qǐng bāng wǒ", russian: "Помогите мне, пожалуйста", level: 1, words: ["请", "帮", "我"] },
    { chinese: "麻烦你了", pinyin: "máfan nǐ le", russian: "Извини за беспокойство", level: 1, words: ["麻", "烦", "你", "了"] },
    { chinese: "辛苦了", pinyin: "xīnkǔ le", russian: "Спасибо за труд", level: 1, words: ["辛", "苦", "了"] },
    { chinese: "慢走", pinyin: "màn zǒu", russian: "Счастливо (уходящему)", level: 1, words: ["慢", "走"] },
    { chinese: "保重", pinyin: "bǎozhòng", russian: "Береги себя", level: 1, words: ["保", "重"] },
    { chinese: "祝你好运", pinyin: "zhù nǐ hǎo yùn", russian: "Удачи тебе", level: 1, words: ["祝", "你", "好", "运"] },
    { chinese: "生日快乐", pinyin: "shēngrì kuàilè", russian: "С днём рождения", level: 1, words: ["生", "日", "快", "乐"] },
    { chinese: "新年快乐", pinyin: "xīnnián kuàilè", russian: "С Новым годом", level: 1, words: ["新", "年", "快", "乐"] },

    // --- Я, ты, он — люди (20) ---
    { chinese: "我是老师", pinyin: "wǒ shì lǎoshī", russian: "Я учитель", level: 1, words: ["我", "是", "老", "师"] },
    { chinese: "我是学生", pinyin: "wǒ shì xuésheng", russian: "Я студент", level: 1, words: ["我", "是", "学", "生"] },
    { chinese: "我叫小明", pinyin: "wǒ jiào Xiǎomíng", russian: "Меня зовут Сяомин", level: 1, words: ["我", "叫", "小", "明"] },
    { chinese: "我姓王", pinyin: "wǒ xìng Wáng", russian: "Моя фамилия Ван", level: 1, words: ["我", "姓", "王"] },
    { chinese: "我是俄罗斯人", pinyin: "wǒ shì Éluósī rén", russian: "Я русский", level: 1, words: ["我", "是", "俄", "罗", "斯", "人"] },
    { chinese: "他是中国人", pinyin: "tā shì Zhōngguó rén", russian: "Он китаец", level: 1, words: ["他", "是", "中", "国", "人"] },
    { chinese: "她是美国人", pinyin: "tā shì Měiguó rén", russian: "Она американка", level: 1, words: ["她", "是", "美", "国", "人"] },
    { chinese: "他是我朋友", pinyin: "tā shì wǒ péngyou", russian: "Он мой друг", level: 1, words: ["他", "是", "我", "朋", "友"] },
    { chinese: "她是我妈妈", pinyin: "tā shì wǒ māma", russian: "Она моя мама", level: 1, words: ["她", "是", "我", "妈", "妈"] },
    { chinese: "这是我爸爸", pinyin: "zhè shì wǒ bàba", russian: "Это мой папа", level: 1, words: ["这", "是", "我", "爸", "爸"] },
    { chinese: "那是我哥哥", pinyin: "nà shì wǒ gēge", russian: "Там мой старший брат", level: 1, words: ["那", "是", "我", "哥", "哥"] },
    { chinese: "她是我姐姐", pinyin: "tā shì wǒ jiějie", russian: "Она моя старшая сестра", level: 1, words: ["她", "是", "我", "姐", "姐"] },
    { chinese: "我有一个弟弟", pinyin: "wǒ yǒu yí ge dìdi", russian: "У меня есть младший брат", level: 1, words: ["我", "有", "一", "个", "弟", "弟"] },
    { chinese: "我没有妹妹", pinyin: "wǒ méiyǒu mèimei", russian: "У меня нет младшей сестры", level: 1, words: ["我", "没", "有", "妹", "妹"] },
    { chinese: "你家有几口人", pinyin: "nǐ jiā yǒu jǐ kǒu rén", russian: "Сколько человек в семье?", level: 1, words: ["你", "家", "有", "几", "口", "人"] },
    { chinese: "我家有四口人", pinyin: "wǒ jiā yǒu sì kǒu rén", russian: "В моей семье 4 человека", level: 1, words: ["我", "家", "有", "四", "口", "人"] },
    { chinese: "你多大了", pinyin: "nǐ duō dà le", russian: "Сколько тебе лет?", level: 1, words: ["你", "多", "大", "了"] },
    { chinese: "我今年二十岁", pinyin: "wǒ jīnnián èrshí suì", russian: "Мне 20 лет", level: 1, words: ["我", "今", "年", "二", "十", "岁"] },
    { chinese: "我住在莫斯科", pinyin: "wǒ zhù zài Mòsīkē", russian: "Я живу в Москве", level: 1, words: ["我", "住", "在", "莫", "斯", "科"] },
    { chinese: "你住在哪里", pinyin: "nǐ zhù zài nǎlǐ", russian: "Где ты живёшь?", level: 1, words: ["你", "住", "在", "哪", "里"] },

    // --- Вопросы и ответы (20) ---
    { chinese: "这是什么", pinyin: "zhè shì shénme", russian: "Что это?", level: 1, words: ["这", "是", "什", "么"] },
    { chinese: "那是谁", pinyin: "nà shì shéi", russian: "Кто там?", level: 1, words: ["那", "是", "谁"] },
    { chinese: "他是谁", pinyin: "tā shì shéi", russian: "Кто он?", level: 1, words: ["他", "是", "谁"] },
    { chinese: "现在几点", pinyin: "xiànzài jǐ diǎn", russian: "Который час?", level: 1, words: ["现", "在", "几", "点"] },
    { chinese: "今天几号", pinyin: "jīntiān jǐ hào", russian: "Какое сегодня число?", level: 1, words: ["今", "天", "几", "号"] },
    { chinese: "今天星期一", pinyin: "jīntiān xīngqī yī", russian: "Сегодня понедельник", level: 1, words: ["今", "天", "星", "期", "一"] },
    { chinese: "明天星期二", pinyin: "míngtiān xīngqī èr", russian: "Завтра вторник", level: 1, words: ["明", "天", "星", "期", "二"] },
    { chinese: "在哪里", pinyin: "zài nǎlǐ", russian: "Где?", level: 1, words: ["在", "哪", "里"] },
    { chinese: "在这里", pinyin: "zài zhèlǐ", russian: "Здесь", level: 1, words: ["在", "这", "里"] },
    { chinese: "在那里", pinyin: "zài nàlǐ", russian: "Там", level: 1, words: ["在", "那", "里"] },
    { chinese: "我不知道", pinyin: "wǒ bù zhīdào", russian: "Я не знаю", level: 1, words: ["我", "不", "知", "道"] },
    { chinese: "我知道", pinyin: "wǒ zhīdào", russian: "Я знаю", level: 1, words: ["我", "知", "道"] },
    { chinese: "我懂了", pinyin: "wǒ dǒng le", russian: "Я понял", level: 1, words: ["我", "懂", "了"] },
    { chinese: "我不懂", pinyin: "wǒ bù dǒng", russian: "Я не понимаю", level: 1, words: ["我", "不", "懂"] },
    { chinese: "我明白了", pinyin: "wǒ míngbai le", russian: "Я понял (ясно)", level: 1, words: ["我", "明", "白", "了"] },
    { chinese: "什么意思", pinyin: "shénme yìsi", russian: "Что это значит?", level: 1, words: ["什", "么", "意", "思"] },
    { chinese: "对不对", pinyin: "duì bu duì", russian: "Правильно?", level: 1, words: ["对", "不", "对"] },
    { chinese: "对不对", pinyin: "duì bu duì", russian: "Верно?", level: 1, words: ["对", "不", "对"] },
    { chinese: "是的", pinyin: "shì de", russian: "Да", level: 1, words: ["是", "的"] },
    { chinese: "不是", pinyin: "bú shì", russian: "Нет", level: 1, words: ["不", "是"] },

    // --- Чувства и состояния (15) ---
    { chinese: "我很好", pinyin: "wǒ hěn hǎo", russian: "У меня всё хорошо", level: 1, words: ["我", "很", "好"] },
    { chinese: "我很好", pinyin: "wǒ hěn hǎo", russian: "Я в порядке", level: 1, words: ["我", "很", "好"] },
    { chinese: "还不错", pinyin: "hái búcuò", russian: "Неплохо", level: 1, words: ["还", "不", "错"] },
    { chinese: "马马虎虎", pinyin: "mǎmǎ hǔhǔ", russian: "Так себе", level: 1, words: ["马", "马", "虎", "虎"] },
    { chinese: "我累了", pinyin: "wǒ lèi le", russian: "Я устал", level: 1, words: ["我", "累", "了"] },
    { chinese: "我饿了", pinyin: "wǒ è le", russian: "Я голоден", level: 1, words: ["我", "饿", "了"] },
    { chinese: "我渴了", pinyin: "wǒ kě le", russian: "Я хочу пить", level: 1, words: ["我", "渴", "了"] },
    { chinese: "我困了", pinyin: "wǒ kùn le", russian: "Я хочу спать", level: 1, words: ["我", "困", "了"] },
    { chinese: "我很开心", pinyin: "wǒ hěn kāixīn", russian: "Я очень рад", level: 1, words: ["我", "很", "开", "心"] },
    { chinese: "我很难过", pinyin: "wǒ hěn nánguò", russian: "Мне грустно", level: 1, words: ["我", "很", "难", "过"] },
    { chinese: "我很忙", pinyin: "wǒ hěn máng", russian: "Я очень занят", level: 1, words: ["我", "很", "忙"] },
    { chinese: "我很紧张", pinyin: "wǒ hěn jǐnzhāng", russian: "Я нервничаю", level: 1, words: ["我", "很", "紧", "张"] },
    { chinese: "我生气了", pinyin: "wǒ shēngqì le", russian: "Я злюсь", level: 1, words: ["我", "生", "气", "了"] },
    { chinese: "我害怕", pinyin: "wǒ hàipà", russian: "Мне страшно", level: 1, words: ["我", "害", "怕"] },
    { chinese: "我头疼", pinyin: "wǒ tóuténg", russian: "У меня болит голова", level: 1, words: ["我", "头", "疼"] },

    // --- Действия (10) ---
    { chinese: "请坐", pinyin: "qǐng zuò", russian: "Садитесь", level: 1, words: ["请", "坐"] },
    { chinese: "请站起来", pinyin: "qǐng zhàn qǐlái", russian: "Встаньте, пожалуйста", level: 1, words: ["请", "站", "起", "来"] },
    { chinese: "请开门", pinyin: "qǐng kāi mén", russian: "Откройте дверь", level: 1, words: ["请", "开", "门"] },
    { chinese: "请关门", pinyin: "qǐng guān mén", russian: "Закройте дверь", level: 1, words: ["请", "关", "门"] },
    { chinese: "请说话", pinyin: "qǐng shuōhuà", russian: "Говорите, пожалуйста", level: 1, words: ["请", "说", "话"] },
    { chinese: "请听我说", pinyin: "qǐng tīng wǒ shuō", russian: "Послушайте меня", level: 1, words: ["请", "听", "我", "说"] },
    { chinese: "请看这里", pinyin: "qǐng kàn zhèlǐ", russian: "Посмотрите сюда", level: 1, words: ["请", "看", "这", "里"] },
    { chinese: "请跟我来", pinyin: "qǐng gēn wǒ lái", russian: "Идите за мной", level: 1, words: ["请", "跟", "我", "来"] },
    { chinese: "请拿给我", pinyin: "qǐng ná gěi wǒ", russian: "Подайте мне, пожалуйста", level: 1, words: ["请", "拿", "给", "我"] },
    { chinese: "请告诉我", pinyin: "qǐng gàosu wǒ", russian: "Скажите мне, пожалуйста", level: 1, words: ["请", "告", "诉", "我"] },

    // --- Погода (10) ---
    { chinese: "天气很好", pinyin: "tiānqì hěn hǎo", russian: "Погода хорошая", level: 1, words: ["天", "气", "很", "好"] },
    { chinese: "今天很热", pinyin: "jīntiān hěn rè", russian: "Сегодня жарко", level: 1, words: ["今", "天", "很", "热"] },
    { chinese: "今天很冷", pinyin: "jīntiān hěn lěng", russian: "Сегодня холодно", level: 1, words: ["今", "天", "很", "冷"] },
    { chinese: "下雨了", pinyin: "xià yǔ le", russian: "Пошёл дождь", level: 1, words: ["下", "雨", "了"] },
    { chinese: "下雪了", pinyin: "xià xuě le", russian: "Пошёл снег", level: 1, words: ["下", "雪", "了"] },
    { chinese: "刮风了", pinyin: "guā fēng le", russian: "Подул ветер", level: 1, words: ["刮", "风", "了"] },
    { chinese: "天晴了", pinyin: "tiān qíng le", russian: "Прояснилось", level: 1, words: ["天", "晴", "了"] },
    { chinese: "今天多少度", pinyin: "jīntiān duōshao dù", russian: "Сколько сегодня градусов?", level: 1, words: ["今", "天", "多", "少", "度"] },
    { chinese: "春天来了", pinyin: "chūntiān lái le", russian: "Весна пришла", level: 1, words: ["春", "天", "来", "了"] },
    { chinese: "我喜欢夏天", pinyin: "wǒ xǐhuan xiàtiān", russian: "Я люблю лето", level: 1, words: ["我", "喜", "欢", "夏", "天"] },

    // ==================== УРОВЕНЬ 2 ⭐⭐: ЕДА, ПОКУПКИ, ДОМ, ТРАНСПОРТ (120 фраз) ====================
    // --- Еда и ресторан (30) ---
    { chinese: "我想吃饭", pinyin: "wǒ xiǎng chīfàn", russian: "Я хочу есть", level: 2, words: ["我", "想", "吃", "饭"] },
    { chinese: "你饿了吗", pinyin: "nǐ è le ma", russian: "Ты голоден?", level: 2, words: ["你", "饿", "了", "吗"] },
    { chinese: "我饿了", pinyin: "wǒ è le", russian: "Я голоден", level: 2, words: ["我", "饿", "了"] },
    { chinese: "很好吃", pinyin: "hěn hǎochī", russian: "Очень вкусно", level: 2, words: ["很", "好", "吃"] },
    { chinese: "这个很好吃", pinyin: "zhè ge hěn hǎochī", russian: "Это очень вкусно", level: 2, words: ["这", "个", "很", "好", "吃"] },
    { chinese: "我不喜欢吃鱼", pinyin: "wǒ bù xǐhuan chī yú", russian: "Я не люблю рыбу", level: 2, words: ["我", "不", "喜", "欢", "吃", "鱼"] },
    { chinese: "我要一杯水", pinyin: "wǒ yào yì bēi shuǐ", russian: "Я хочу стакан воды", level: 2, words: ["我", "要", "一", "杯", "水"] },
    { chinese: "请给我菜单", pinyin: "qǐng gěi wǒ càidān", russian: "Дайте меню", level: 2, words: ["请", "给", "我", "菜", "单"] },
    { chinese: "我要点菜", pinyin: "wǒ yào diǎn cài", russian: "Я хочу заказать", level: 2, words: ["我", "要", "点", "菜"] },
    { chinese: "你有什么推荐", pinyin: "nǐ yǒu shénme tuījiàn", russian: "Что посоветуете?", level: 2, words: ["你", "有", "什", "么", "推", "荐"] },
    { chinese: "我要一碗米饭", pinyin: "wǒ yào yì wǎn mǐfàn", russian: "Я хочу чашку риса", level: 2, words: ["我", "要", "一", "碗", "米", "饭"] },
    { chinese: "我要一瓶啤酒", pinyin: "wǒ yào yì píng píjiǔ", russian: "Я хочу бутылку пива", level: 2, words: ["我", "要", "一", "瓶", "啤", "酒"] },
    { chinese: "干杯", pinyin: "gān bēi", russian: "До дна!", level: 2, words: ["干", "杯"] },
    { chinese: "你吃辣吗", pinyin: "nǐ chī là ma", russian: "Ты ешь острое?", level: 2, words: ["你", "吃", "辣", "吗"] },
    { chinese: "我不吃肉", pinyin: "wǒ bù chī ròu", russian: "Я не ем мясо", level: 2, words: ["我", "不", "吃", "肉"] },
    { chinese: "我吃素", pinyin: "wǒ chī sù", russian: "Я вегетарианец", level: 2, words: ["我", "吃", "素"] },
    { chinese: "少放盐", pinyin: "shǎo fàng yán", russian: "Меньше соли", level: 2, words: ["少", "放", "盐"] },
    { chinese: "不要太辣", pinyin: "búyào tài là", russian: "Не слишком остро", level: 2, words: ["不", "要", "太", "辣"] },
    { chinese: "买单", pinyin: "mǎidān", russian: "Счёт, пожалуйста", level: 2, words: ["买", "单"] },
    { chinese: "可以打包吗", pinyin: "kěyǐ dǎbāo ma", russian: "Можно с собой?", level: 2, words: ["可", "以", "打", "包", "吗"] },
    { chinese: "服务员", pinyin: "fúwùyuán", russian: "Официант!", level: 2, words: ["服", "务", "员"] },
    { chinese: "今天有什么特价菜", pinyin: "jīntiān yǒu shénme tèjià cài", russian: "Какие сегодня спецпредложения?", level: 2, words: ["今", "天", "有", "什", "么", "特", "价", "菜"] },
    { chinese: "请再来一碗饭", pinyin: "qǐng zài lái yì wǎn fàn", russian: "Ещё одну чашку риса", level: 2, words: ["请", "再", "来", "一", "碗", "饭"] },
    { chinese: "我吃饱了", pinyin: "wǒ chī bǎo le", russian: "Я наелся", level: 2, words: ["我", "吃", "饱", "了"] },
    { chinese: "很好吃，谢谢", pinyin: "hěn hǎochī, xièxie", russian: "Очень вкусно, спасибо", level: 2, words: ["很", "好", "吃", "谢", "谢"] },
    { chinese: "你们有筷子吗", pinyin: "nǐmen yǒu kuàizi ma", russian: "У вас есть палочки?", level: 2, words: ["你", "们", "有", "筷", "子", "吗"] },
    { chinese: "请给我餐巾纸", pinyin: "qǐng gěi wǒ cānjīnzhǐ", russian: "Дайте салфетку", level: 2, words: ["请", "给", "我", "餐", "巾", "纸"] },
    { chinese: "早餐几点开始", pinyin: "zǎocān jǐ diǎn kāishǐ", russian: "Во сколько завтрак?", level: 2, words: ["早", "餐", "几", "点", "开", "始"] },
    { chinese: "我订了位子", pinyin: "wǒ dìng le wèizi", russian: "Я забронировал столик", level: 2, words: ["我", "订", "了", "位", "子"] },
    { chinese: "一共多少钱", pinyin: "yígòng duōshao qián", russian: "Сколько всего?", level: 2, words: ["一", "共", "多", "少", "钱"] },

    // --- Покупки (30) ---
    { chinese: "这个多少钱", pinyin: "zhè ge duōshao qián", russian: "Сколько это стоит?", level: 2, words: ["这", "个", "多", "少", "钱"] },
    { chinese: "太贵了", pinyin: "tài guì le", russian: "Слишком дорого", level: 2, words: ["太", "贵", "了"] },
    { chinese: "便宜一点吧", pinyin: "piányi yìdiǎn ba", russian: "Немного дешевле", level: 2, words: ["便", "宜", "一", "点", "吧"] },
    { chinese: "可以打折吗", pinyin: "kěyǐ dǎzhé ma", russian: "Можно скидку?", level: 2, words: ["可", "以", "打", "折", "吗"] },
    { chinese: "我想买一件衣服", pinyin: "wǒ xiǎng mǎi yí jiàn yīfu", russian: "Я хочу купить одежду", level: 2, words: ["我", "想", "买", "一", "件", "衣", "服"] },
    { chinese: "我可以试试吗", pinyin: "wǒ kěyǐ shì shì ma", russian: "Можно примерить?", level: 2, words: ["我", "可", "以", "试", "试", "吗"] },
    { chinese: "试衣间在哪里", pinyin: "shìyījiān zài nǎlǐ", russian: "Где примерочная?", level: 2, words: ["试", "衣", "间", "在", "哪", "里"] },
    { chinese: "有没有大一点的", pinyin: "yǒu méiyǒu dà yìdiǎn de", russian: "Есть побольше размер?", level: 2, words: ["有", "没", "有", "大", "一", "点", "的"] },
    { chinese: "有没有小一点的", pinyin: "yǒu méiyǒu xiǎo yìdiǎn de", russian: "Есть поменьше?", level: 2, words: ["有", "没", "有", "小", "一", "点", "的"] },
    { chinese: "我要这个", pinyin: "wǒ yào zhè ge", russian: "Я возьму это", level: 2, words: ["我", "要", "这", "个"] },
    { chinese: "可以刷卡吗", pinyin: "kěyǐ shuākǎ ma", russian: "Можно картой?", level: 2, words: ["可", "以", "刷", "卡", "吗"] },
    { chinese: "我付现金", pinyin: "wǒ fù xiànjīn", russian: "Я заплачу наличными", level: 2, words: ["我", "付", "现", "金"] },
    { chinese: "请给我发票", pinyin: "qǐng gěi wǒ fāpiào", russian: "Дайте чек", level: 2, words: ["请", "给", "我", "发", "票"] },
    { chinese: "有没有别的颜色", pinyin: "yǒu méiyǒu bié de yánsè", russian: "Есть другие цвета?", level: 2, words: ["有", "没", "有", "别", "的", "颜", "色"] },
    { chinese: "这个是什么材料", pinyin: "zhè ge shì shénme cáiliào", russian: "Какой это материал?", level: 2, words: ["这", "个", "是", "什", "么", "材", "料"] },
    { chinese: "可以退换吗", pinyin: "kěyǐ tuìhuàn ma", russian: "Можно вернуть или обменять?", level: 2, words: ["可", "以", "退", "换", "吗"] },
    { chinese: "我去超市", pinyin: "wǒ qù chāoshì", russian: "Я иду в супермаркет", level: 2, words: ["我", "去", "超", "市"] },
    { chinese: "超市在楼下", pinyin: "chāoshì zài lóu xià", russian: "Супермаркет внизу", level: 2, words: ["超", "市", "在", "楼", "下"] },
    { chinese: "我要买水果", pinyin: "wǒ yào mǎi shuǐguǒ", russian: "Я хочу купить фрукты", level: 2, words: ["我", "要", "买", "水", "果"] },
    { chinese: "苹果多少钱一斤", pinyin: "píngguǒ duōshao qián yì jīn", russian: "Сколько стоят яблоки за цзинь?", level: 2, words: ["苹", "果", "多", "少", "钱", "一", "斤"] },
    { chinese: "可以微信支付吗", pinyin: "kěyǐ Wēixìn zhīfù ma", russian: "Можно заплатить через WeChat?", level: 2, words: ["可", "以", "微", "信", "支", "付", "吗"] },
    { chinese: "支付宝可以吗", pinyin: "Zhīfùbǎo kěyǐ ma", russian: "Можно через Alipay?", level: 2, words: ["支", "付", "宝", "可", "以", "吗"] },
    { chinese: "请给我一个袋子", pinyin: "qǐng gěi wǒ yí ge dàizi", russian: "Дайте пакет", level: 2, words: ["请", "给", "我", "一", "个", "袋", "子"] },
    { chinese: "不用袋子了", pinyin: "búyòng dàizi le", russian: "Пакет не нужен", level: 2, words: ["不", "用", "袋", "子", "了"] },
    { chinese: "收银台在哪里", pinyin: "shōuyíntái zài nǎlǐ", russian: "Где касса?", level: 2, words: ["收", "银", "台", "在", "哪", "里"] },
    { chinese: "这个有保修吗", pinyin: "zhè ge yǒu bǎoxiū ma", russian: "На это есть гарантия?", level: 2, words: ["这", "个", "有", "保", "修", "吗"] },
    { chinese: "我在找礼物", pinyin: "wǒ zài zhǎo lǐwù", russian: "Я ищу подарок", level: 2, words: ["我", "在", "找", "礼", "物"] },
    { chinese: "多少钱一公斤", pinyin: "duōshao qián yì gōngjīn", russian: "Сколько за килограмм?", level: 2, words: ["多", "少", "钱", "一", "公", "斤"] },
    { chinese: "太便宜了", pinyin: "tài piányi le", russian: "Очень дёшево", level: 2, words: ["太", "便", "宜", "了"] },
    { chinese: "我只看不买", pinyin: "wǒ zhǐ kàn bù mǎi", russian: "Я просто смотрю", level: 2, words: ["我", "只", "看", "不", "买"] },

    // --- Транспорт (30) ---
    { chinese: "我去北京", pinyin: "wǒ qù Běijīng", russian: "Я еду в Пекин", level: 2, words: ["我", "去", "北", "京"] },
    { chinese: "怎么去火车站", pinyin: "zěnme qù huǒchēzhàn", russian: "Как пройти на вокзал?", level: 2, words: ["怎", "么", "去", "火", "车", "站"] },
    { chinese: "地铁站在哪里", pinyin: "dìtiě zhàn zài nǎlǐ", russian: "Где метро?", level: 2, words: ["地", "铁", "站", "在", "哪", "里"] },
    { chinese: "我坐地铁去上班", pinyin: "wǒ zuò dìtiě qù shàngbān", russian: "Я еду на метро на работу", level: 2, words: ["我", "坐", "地", "铁", "去", "上", "班"] },
    { chinese: "请问附近有公交站吗", pinyin: "qǐngwèn fùjìn yǒu gōngjiāo zhàn ma", russian: "Рядом есть остановка?", level: 2, words: ["请", "问", "附", "近", "有", "公", "交", "站", "吗"] },
    { chinese: "一直走然后右拐", pinyin: "yìzhí zǒu ránhòu yòu guǎi", russian: "Идите прямо, потом направо", level: 2, words: ["一", "直", "走", "然", "后", "右", "拐"] },
    { chinese: "离这里远不远", pinyin: "lí zhèlǐ yuǎn bù yuǎn", russian: "Далеко отсюда?", level: 2, words: ["离", "这", "里", "远", "不", "远"] },
    { chinese: "我迷路了", pinyin: "wǒ mílù le", russian: "Я заблудился", level: 2, words: ["我", "迷", "路", "了"] },
    { chinese: "一张去上海的票", pinyin: "yì zhāng qù Shànghǎi de piào", russian: "Один билет до Шанхая", level: 2, words: ["一", "张", "去", "上", "海", "的", "票"] },
    { chinese: "飞机几点起飞", pinyin: "fēijī jǐ diǎn qǐfēi", russian: "Во сколько вылет?", level: 2, words: ["飞", "机", "几", "点", "起", "飞"] },
    { chinese: "请送我到机场", pinyin: "qǐng sòng wǒ dào jīchǎng", russian: "Отвезите в аэропорт", level: 2, words: ["请", "送", "我", "到", "机", "场"] },
    { chinese: "这里可以停车吗", pinyin: "zhèlǐ kěyǐ tíngchē ma", russian: "Можно парковаться?", level: 2, words: ["这", "里", "可", "以", "停", "车", "吗"] },
    { chinese: "打车去要多长时间", pinyin: "dǎchē qù yào duō cháng shíjiān", russian: "Сколько ехать на такси?", level: 2, words: ["打", "车", "去", "要", "多", "长", "时", "间"] },
    { chinese: "请打表", pinyin: "qǐng dǎ biǎo", russian: "Включите счётчик", level: 2, words: ["请", "打", "表"] },
    { chinese: "在这里停就可以了", pinyin: "zài zhèlǐ tíng jiù kěyǐ le", russian: "Остановите здесь", level: 2, words: ["在", "这", "里", "停", "就", "可", "以", "了"] },
    { chinese: "我要去机场", pinyin: "wǒ yào qù jīchǎng", russian: "Мне нужно в аэропорт", level: 2, words: ["我", "要", "去", "机", "场"] },
    { chinese: "哪个出口", pinyin: "nǎ ge chūkǒu", russian: "Какой выход?", level: 2, words: ["哪", "个", "出", "口"] },
    { chinese: "我在哪里下车", pinyin: "wǒ zài nǎlǐ xià chē", russian: "Где мне выходить?", level: 2, words: ["我", "在", "哪", "里", "下", "车"] },
    { chinese: "末班车几点", pinyin: "mòbān chē jǐ diǎn", russian: "Во сколько последний поезд?", level: 2, words: ["末", "班", "车", "几", "点"] },
    { chinese: "有直达车吗", pinyin: "yǒu zhídá chē ma", russian: "Есть прямой поезд?", level: 2, words: ["有", "直", "达", "车", "吗"] },
    { chinese: "需要换乘吗", pinyin: "xūyào huànchéng ma", russian: "Нужна пересадка?", level: 2, words: ["需", "要", "换", "乘", "吗"] },
    { chinese: "这是几号线", pinyin: "zhè shì jǐ hào xiàn", russian: "Это какая линия?", level: 2, words: ["这", "是", "几", "号", "线"] },
    { chinese: "我要去火车站", pinyin: "wǒ yào qù huǒchēzhàn", russian: "Мне на вокзал", level: 2, words: ["我", "要", "去", "火", "车", "站"] },
    { chinese: "我能走过去吗", pinyin: "wǒ néng zǒu guòqù ma", russian: "Можно дойти пешком?", level: 2, words: ["我", "能", "走", "过", "去", "吗"] },
    { chinese: "有地图吗", pinyin: "yǒu dìtú ma", russian: "У вас есть карта?", level: 2, words: ["有", "地", "图", "吗"] },
    { chinese: "我找不到路了", pinyin: "wǒ zhǎo bú dào lù le", russian: "Я не могу найти дорогу", level: 2, words: ["我", "找", "不", "到", "路", "了"] },
    { chinese: "红绿灯在哪里", pinyin: "hónglǜdēng zài nǎlǐ", russian: "Где светофор?", level: 2, words: ["红", "绿", "灯", "在", "哪", "里"] },
    { chinese: "可以骑共享单车吗", pinyin: "kěyǐ qí gòngxiǎng dānchē ma", russian: "Можно поехать на велопрокате?", level: 2, words: ["可", "以", "骑", "共", "享", "单", "车", "吗"] },
    { chinese: "加油站在哪里", pinyin: "jiāyóu zhàn zài nǎlǐ", russian: "Где заправка?", level: 2, words: ["加", "油", "站", "在", "哪", "里"] },
    { chinese: "我赶时间", pinyin: "wǒ gǎn shíjiān", russian: "Я спешу", level: 2, words: ["我", "赶", "时", "间"] },

    // --- Дом и отель (30) ---
    { chinese: "我要订一个房间", pinyin: "wǒ yào dìng yí ge fángjiān", russian: "Хочу забронировать номер", level: 2, words: ["我", "要", "订", "一", "个", "房", "间"] },
    { chinese: "有没有空房间", pinyin: "yǒu méiyǒu kòng fángjiān", russian: "Есть свободные номера?", level: 2, words: ["有", "没", "有", "空", "房", "间"] },
    { chinese: "我要住两晚", pinyin: "wǒ yào zhù liǎng wǎn", russian: "Я останусь на две ночи", level: 2, words: ["我", "要", "住", "两", "晚"] },
    { chinese: "房间有WiFi吗", pinyin: "fángjiān yǒu WiFi ma", russian: "В номере есть WiFi?", level: 2, words: ["房", "间", "有", "WiFi", "吗"] },
    { chinese: "密码是多少", pinyin: "mìmǎ shì duōshao", russian: "Какой пароль?", level: 2, words: ["密", "码", "是", "多", "少"] },
    { chinese: "空调坏了", pinyin: "kōngtiáo huài le", russian: "Кондиционер сломался", level: 2, words: ["空", "调", "坏", "了"] },
    { chinese: "没有热水", pinyin: "méiyǒu rè shuǐ", russian: "Нет горячей воды", level: 2, words: ["没", "有", "热", "水"] },
    { chinese: "请打扫房间", pinyin: "qǐng dǎsǎo fángjiān", russian: "Уберите номер, пожалуйста", level: 2, words: ["请", "打", "扫", "房", "间"] },
    { chinese: "我要退房", pinyin: "wǒ yào tuì fáng", russian: "Я выезжаю", level: 2, words: ["我", "要", "退", "房"] },
    { chinese: "早餐几点开始", pinyin: "zǎocān jǐ diǎn kāishǐ", russian: "Во сколько завтрак?", level: 2, words: ["早", "餐", "几", "点", "开", "始"] },
    { chinese: "可以叫醒我吗", pinyin: "kěyǐ jiàoxǐng wǒ ma", russian: "Можете разбудить?", level: 2, words: ["可", "以", "叫", "醒", "我", "吗"] },
    { chinese: "请给我毛巾", pinyin: "qǐng gěi wǒ máojīn", russian: "Дайте полотенце", level: 2, words: ["请", "给", "我", "毛", "巾"] },
    { chinese: "我到家了", pinyin: "wǒ dào jiā le", russian: "Я пришёл домой", level: 2, words: ["我", "到", "家", "了"] },
    { chinese: "请把门锁上", pinyin: "qǐng bǎ mén suǒ shàng", russian: "Запри дверь", level: 2, words: ["请", "把", "门", "锁", "上"] },
    { chinese: "请把灯打开", pinyin: "qǐng bǎ dēng dǎkāi", russian: "Включи свет", level: 2, words: ["请", "把", "灯", "打", "开"] },
    { chinese: "请把窗户关上", pinyin: "qǐng bǎ chuānghu guān shàng", russian: "Закрой окно", level: 2, words: ["请", "把", "窗", "户", "关", "上"] },
    { chinese: "你家很大", pinyin: "nǐ jiā hěn dà", russian: "У тебя большой дом", level: 2, words: ["你", "家", "很", "大"] },
    { chinese: "我的房间在楼上", pinyin: "wǒ de fángjiān zài lóu shàng", russian: "Моя комната наверху", level: 2, words: ["我", "的", "房", "间", "在", "楼", "上"] },
    { chinese: "客厅在哪里", pinyin: "kètīng zài nǎlǐ", russian: "Где гостиная?", level: 2, words: ["客", "厅", "在", "哪", "里"] },
    { chinese: "厨房在左边", pinyin: "chúfáng zài zuǒbiān", russian: "Кухня слева", level: 2, words: ["厨", "房", "在", "左", "边"] },
    { chinese: "厕所在这边", pinyin: "cèsuǒ zài zhè biān", russian: "Туалет здесь", level: 2, words: ["厕", "所", "在", "这", "边"] },
    { chinese: "请换床单", pinyin: "qǐng huàn chuángdān", russian: "Поменяйте постель", level: 2, words: ["请", "换", "床", "单"] },
    { chinese: "我洗个澡", pinyin: "wǒ xǐ ge zǎo", russian: "Я приму душ", level: 2, words: ["我", "洗", "个", "澡"] },
    { chinese: "我睡得很晚", pinyin: "wǒ shuì de hěn wǎn", russian: "Я поздно лёг", level: 2, words: ["我", "睡", "得", "很", "晚"] },
    { chinese: "我起得很早", pinyin: "wǒ qǐ de hěn zǎo", russian: "Я рано встаю", level: 2, words: ["我", "起", "得", "很", "早"] },
    { chinese: "今天我在家工作", pinyin: "jīntiān wǒ zài jiā gōngzuò", russian: "Сегодня работаю из дома", level: 2, words: ["今", "天", "我", "在", "家", "工", "作"] },
    { chinese: "欢迎来我家", pinyin: "huānyíng lái wǒ jiā", russian: "Добро пожаловать ко мне", level: 2, words: ["欢", "迎", "来", "我", "家"] },
    { chinese: "随便坐", pinyin: "suíbiàn zuò", russian: "Садись где хочешь", level: 2, words: ["随", "便", "坐"] },
    { chinese: "我去开门", pinyin: "wǒ qù kāi mén", russian: "Я открою дверь", level: 2, words: ["我", "去", "开", "门"] },
    { chinese: "有人敲门", pinyin: "yǒu rén qiāo mén", russian: "Кто-то стучит", level: 2, words: ["有", "人", "敲", "门"] }
];
// ==================== УРОВЕНЬ 3 ⭐⭐⭐: РАБОТА, УЧЁБА, ЗДОРОВЬЕ (120 фраз) ====================
    // --- Работа (30) ---
    { chinese: "我上班去了", pinyin: "wǒ shàngbān qù le", russian: "Я пошёл на работу", level: 3, words: ["我", "上", "班", "去", "了"] },
    { chinese: "我下班了", pinyin: "wǒ xiàbān le", russian: "Я с работы", level: 3, words: ["我", "下", "班", "了"] },
    { chinese: "今天加班吗", pinyin: "jīntiān jiābān ma", russian: "Сегодня сверхурочно?", level: 3, words: ["今", "天", "加", "班", "吗"] },
    { chinese: "我有很多工作", pinyin: "wǒ yǒu hěn duō gōngzuò", russian: "У меня много работы", level: 3, words: ["我", "有", "很", "多", "工", "作"] },
    { chinese: "老板在吗", pinyin: "lǎobǎn zài ma", russian: "Начальник на месте?", level: 3, words: ["老", "板", "在", "吗"] },
    { chinese: "开会了", pinyin: "kāihuì le", russian: "Собрание началось", level: 3, words: ["开", "会", "了"] },
    { chinese: "请把文件发给我", pinyin: "qǐng bǎ wénjiàn fā gěi wǒ", russian: "Пришли документы", level: 3, words: ["请", "把", "文", "件", "发", "给", "我"] },
    { chinese: "我收到了", pinyin: "wǒ shōudào le", russian: "Я получил", level: 3, words: ["我", "收", "到", "了"] },
    { chinese: "请稍等", pinyin: "qǐng shāo děng", russian: "Подождите немного", level: 3, words: ["请", "稍", "等"] },
    { chinese: "这个怎么用", pinyin: "zhè ge zěnme yòng", russian: "Как это использовать?", level: 3, words: ["这", "个", "怎", "么", "用"] },
    { chinese: "打印机坏了", pinyin: "dǎyìnjī huài le", russian: "Принтер сломался", level: 3, words: ["打", "印", "机", "坏", "了"] },
    { chinese: "电脑死机了", pinyin: "diànnǎo sǐjī le", russian: "Компьютер завис", level: 3, words: ["电", "脑", "死", "机", "了"] },
    { chinese: "网络连不上", pinyin: "wǎngluò lián bú shàng", russian: "Интернет не подключается", level: 3, words: ["网", "络", "连", "不", "上"] },
    { chinese: "我需要帮助", pinyin: "wǒ xūyào bāngzhù", russian: "Мне нужна помощь", level: 3, words: ["我", "需", "要", "帮", "助"] },
    { chinese: "谁负责这个", pinyin: "shéi fùzé zhè ge", russian: "Кто за это отвечает?", level: 3, words: ["谁", "负", "责", "这", "个"] },
    { chinese: "我有个问题", pinyin: "wǒ yǒu ge wèntí", russian: "У меня вопрос", level: 3, words: ["我", "有", "个", "问", "题"] },
    { chinese: "可以解释一下吗", pinyin: "kěyǐ jiěshì yíxià ma", russian: "Можете объяснить?", level: 3, words: ["可", "以", "解", "释", "一", "下", "吗"] },
    { chinese: "我不太明白", pinyin: "wǒ bú tài míngbai", russian: "Не совсем понимаю", level: 3, words: ["我", "不", "太", "明", "白"] },
    { chinese: "请再说一遍", pinyin: "qǐng zài shuō yí biàn", russian: "Повторите ещё раз", level: 3, words: ["请", "再", "说", "一", "遍"] },
    { chinese: "我明天请假", pinyin: "wǒ míngtiān qǐngjià", russian: "Завтра я беру выходной", level: 3, words: ["我", "明", "天", "请", "假"] },
    { chinese: "今天发工资", pinyin: "jīntiān fā gōngzī", russian: "Сегодня зарплата", level: 3, words: ["今", "天", "发", "工", "资"] },
    { chinese: "我很满意这份工作", pinyin: "wǒ hěn mǎnyì zhè fèn gōngzuò", russian: "Я доволен работой", level: 3, words: ["我", "很", "满", "意", "这", "份", "工", "作"] },
    { chinese: "我想换工作", pinyin: "wǒ xiǎng huàn gōngzuò", russian: "Хочу сменить работу", level: 3, words: ["我", "想", "换", "工", "作"] },
    { chinese: "有加班费吗", pinyin: "yǒu jiābān fèi ma", russian: "Есть ли оплата сверхурочных?", level: 3, words: ["有", "加", "班", "费", "吗"] },
    { chinese: "请签字", pinyin: "qǐng qiān zì", russian: "Подпишите, пожалуйста", level: 3, words: ["请", "签", "字"] },
    { chinese: "合同准备好了吗", pinyin: "hétong zhǔnbèi hǎo le ma", russian: "Договор готов?", level: 3, words: ["合", "同", "准", "备", "好", "了", "吗"] },
    { chinese: "这是什么意思", pinyin: "zhè shì shénme yìsi", russian: "Что это значит?", level: 3, words: ["这", "是", "什", "么", "意", "思"] },
    { chinese: "我不同意的", pinyin: "wǒ bù tóngyì de", russian: "Я не согласен", level: 3, words: ["我", "不", "同", "意", "的"] },
    { chinese: "让我想一想", pinyin: "ràng wǒ xiǎng yì xiǎng", russian: "Дай подумать", level: 3, words: ["让", "我", "想", "一", "想"] },
    { chinese: "这个方案不错", pinyin: "zhè ge fāng'àn búcuò", russian: "Этот план неплох", level: 3, words: ["这", "个", "方", "案", "不", "错"] },

    // --- Учёба (30) ---
    { chinese: "我在学习汉语", pinyin: "wǒ zài xuéxí hànyǔ", russian: "Я учу китайский", level: 3, words: ["我", "在", "学", "习", "汉", "语"] },
    { chinese: "我每天学一个小时", pinyin: "wǒ měitiān xué yí ge xiǎoshí", russian: "Я учу час каждый день", level: 3, words: ["我", "每", "天", "学", "一", "个", "小", "时"] },
    { chinese: "这个字怎么写", pinyin: "zhè ge zì zěnme xiě", russian: "Как пишется этот иероглиф?", level: 3, words: ["这", "个", "字", "怎", "么", "写"] },
    { chinese: "这个字怎么读", pinyin: "zhè ge zì zěnme dú", russian: "Как читается этот иероглиф?", level: 3, words: ["这", "个", "字", "怎", "么", "读"] },
    { chinese: "请慢一点说", pinyin: "qǐng màn yìdiǎn shuō", russian: "Говорите медленнее", level: 3, words: ["请", "慢", "一", "点", "说"] },
    { chinese: "我听不懂", pinyin: "wǒ tīng bu dǒng", russian: "Я не понимаю на слух", level: 3, words: ["我", "听", "不", "懂"] },
    { chinese: "这个用中文怎么说", pinyin: "zhè ge yòng zhōngwén zěnme shuō", russian: "Как это по-китайски?", level: 3, words: ["这", "个", "用", "中", "文", "怎", "么", "说"] },
    { chinese: "我会说一点中文", pinyin: "wǒ huì shuō yìdiǎn zhōngwén", russian: "Я немного говорю по-китайски", level: 3, words: ["我", "会", "说", "一", "点", "中", "文"] },
    { chinese: "我不会说中文", pinyin: "wǒ bú huì shuō zhōngwén", russian: "Я не говорю по-китайски", level: 3, words: ["我", "不", "会", "说", "中", "文"] },
    { chinese: "你在哪里学的中文", pinyin: "nǐ zài nǎlǐ xué de zhōngwén", russian: "Где ты учил китайский?", level: 3, words: ["你", "在", "哪", "里", "学", "的", "中", "文"] },
    { chinese: "我学过两年汉语", pinyin: "wǒ xué guo liǎng nián hànyǔ", russian: "Я учил китайский два года", level: 3, words: ["我", "学", "过", "两", "年", "汉", "语"] },
    { chinese: "你考了多少分", pinyin: "nǐ kǎo le duōshao fēn", russian: "Сколько баллов ты набрал?", level: 3, words: ["你", "考", "了", "多", "少", "分"] },
    { chinese: "我通过了考试", pinyin: "wǒ tōngguò le kǎoshì", russian: "Я сдал экзамен", level: 3, words: ["我", "通", "过", "了", "考", "试"] },
    { chinese: "考试很难", pinyin: "kǎoshì hěn nán", russian: "Экзамен трудный", level: 3, words: ["考", "试", "很", "难"] },
    { chinese: "明天有考试", pinyin: "míngtiān yǒu kǎoshì", russian: "Завтра экзамен", level: 3, words: ["明", "天", "有", "考", "试"] },
    { chinese: "我要复习功课", pinyin: "wǒ yào fùxí gōngkè", russian: "Мне нужно повторять уроки", level: 3, words: ["我", "要", "复", "习", "功", "课"] },
    { chinese: "请把作业交上来", pinyin: "qǐng bǎ zuòyè jiāo shànglái", russian: "Сдайте домашнее задание", level: 3, words: ["请", "把", "作", "业", "交", "上", "来"] },
    { chinese: "我没写作业", pinyin: "wǒ méi xiě zuòyè", russian: "Я не сделал домашку", level: 3, words: ["我", "没", "写", "作", "业"] },
    { chinese: "这是什么意思", pinyin: "zhè shì shénme yìsi", russian: "Что это значит?", level: 3, words: ["这", "是", "什", "么", "意", "思"] },
    { chinese: "可以举个例子吗", pinyin: "kěyǐ jǔ ge lìzi ma", russian: "Можете привести пример?", level: 3, words: ["可", "以", "举", "个", "例", "子", "吗"] },
    { chinese: "我想提高口语", pinyin: "wǒ xiǎng tígāo kǒuyǔ", russian: "Хочу улучшить разговорный", level: 3, words: ["我", "想", "提", "高", "口", "语"] },
    { chinese: "请纠正我", pinyin: "qǐng jiūzhèng wǒ", russian: "Поправляйте меня", level: 3, words: ["请", "纠", "正", "我"] },
    { chinese: "我有进步吗", pinyin: "wǒ yǒu jìnbù ma", russian: "У меня есть прогресс?", level: 3, words: ["我", "有", "进", "步", "吗"] },
    { chinese: "这个发音对吗", pinyin: "zhè ge fāyīn duì ma", russian: "Это правильное произношение?", level: 3, words: ["这", "个", "发", "音", "对", "吗"] },
    { chinese: "声调很重要", pinyin: "shēngdiào hěn zhòngyào", russian: "Тоны очень важны", level: 3, words: ["声", "调", "很", "重", "要"] },
    { chinese: "我忘了这个字", pinyin: "wǒ wàng le zhè ge zì", russian: "Я забыл этот иероглиф", level: 3, words: ["我", "忘", "了", "这", "个", "字"] },
    { chinese: "请再说一遍", pinyin: "qǐng zài shuō yí biàn", russian: "Повторите ещё раз", level: 3, words: ["请", "再", "说", "一", "遍"] },
    { chinese: "我记住了", pinyin: "wǒ jì zhù le", russian: "Я запомнил", level: 3, words: ["我", "记", "住", "了"] },
    { chinese: "我可以用词典吗", pinyin: "wǒ kěyǐ yòng cídiǎn ma", russian: "Можно использовать словарь?", level: 3, words: ["我", "可", "以", "用", "词", "典", "吗"] },
    { chinese: "学习语言很有趣", pinyin: "xuéxí yǔyán hěn yǒuqù", russian: "Учить язык интересно", level: 3, words: ["学", "习", "语", "言", "很", "有", "趣"] },

    // --- Здоровье (30) ---
    { chinese: "我头疼", pinyin: "wǒ tóuténg", russian: "У меня болит голова", level: 3, words: ["我", "头", "疼"] },
    { chinese: "我肚子疼", pinyin: "wǒ dùzi téng", russian: "У меня болит живот", level: 3, words: ["我", "肚", "子", "疼"] },
    { chinese: "我感冒了", pinyin: "wǒ gǎnmào le", russian: "Я простудился", level: 3, words: ["我", "感", "冒", "了"] },
    { chinese: "我发烧了", pinyin: "wǒ fāshāo le", russian: "У меня температура", level: 3, words: ["我", "发", "烧", "了"] },
    { chinese: "我咳嗽", pinyin: "wǒ késou", russian: "Я кашляю", level: 3, words: ["我", "咳", "嗽"] },
    { chinese: "我需要看医生", pinyin: "wǒ xūyào kàn yīshēng", russian: "Мне нужно к врачу", level: 3, words: ["我", "需", "要", "看", "医", "生"] },
    { chinese: "医院在哪里", pinyin: "yīyuàn zài nǎlǐ", russian: "Где больница?", level: 3, words: ["医", "院", "在", "哪", "里"] },
    { chinese: "请叫救护车", pinyin: "qǐng jiào jiùhù chē", russian: "Вызовите скорую", level: 3, words: ["请", "叫", "救", "护", "车"] },
    { chinese: "我过敏", pinyin: "wǒ guòmǐn", russian: "У меня аллергия", level: 3, words: ["我", "过", "敏"] },
    { chinese: "我不舒服", pinyin: "wǒ bù shūfu", russian: "Мне нехорошо", level: 3, words: ["我", "不", "舒", "服"] },
    { chinese: "请给我药", pinyin: "qǐng gěi wǒ yào", russian: "Дайте лекарство", level: 3, words: ["请", "给", "我", "药"] },
    { chinese: "每天吃几次", pinyin: "měitiān chī jǐ cì", russian: "Сколько раз в день принимать?", level: 3, words: ["每", "天", "吃", "几", "次"] },
    { chinese: "一次吃几片", pinyin: "yí cì chī jǐ piàn", russian: "По сколько таблеток за раз?", level: 3, words: ["一", "次", "吃", "几", "片"] },
    { chinese: "我有保险", pinyin: "wǒ yǒu bǎoxiǎn", russian: "У меня есть страховка", level: 3, words: ["我", "有", "保", "险"] },
    { chinese: "请量体温", pinyin: "qǐng liáng tǐwēn", russian: "Измерьте температуру", level: 3, words: ["请", "量", "体", "温"] },
    { chinese: "我对青霉素过敏", pinyin: "wǒ duì qīngméisù guòmǐn", russian: "У меня аллергия на пенициллин", level: 3, words: ["我", "对", "青", "霉", "素", "过", "敏"] },
    { chinese: "我有高血压", pinyin: "wǒ yǒu gāoxuèyā", russian: "У меня высокое давление", level: 3, words: ["我", "有", "高", "血", "压"] },
    { chinese: "我需要休息", pinyin: "wǒ xūyào xiūxi", russian: "Мне нужно отдохнуть", level: 3, words: ["我", "需", "要", "休", "息"] },
    { chinese: "我失眠了", pinyin: "wǒ shīmián le", russian: "У меня бессонница", level: 3, words: ["我", "失", "眠", "了"] },
    { chinese: "我压力很大", pinyin: "wǒ yālì hěn dà", russian: "У меня сильный стресс", level: 3, words: ["我", "压", "力", "很", "大"] },
    { chinese: "我牙疼", pinyin: "wǒ yá téng", russian: "У меня болит зуб", level: 3, words: ["我", "牙", "疼"] },
    { chinese: "牙医在哪里", pinyin: "yáyī zài nǎlǐ", russian: "Где зубной врач?", level: 3, words: ["牙", "医", "在", "哪", "里"] },
    { chinese: "我昨天受伤了", pinyin: "wǒ zuótiān shòushāng le", russian: "Я вчера поранился", level: 3, words: ["我", "昨", "天", "受", "伤", "了"] },
    { chinese: "这里很疼", pinyin: "zhèlǐ hěn téng", russian: "Здесь очень болит", level: 3, words: ["这", "里", "很", "疼"] },
    { chinese: "我晕倒了", pinyin: "wǒ yūndǎo le", russian: "Я упал в обморок", level: 3, words: ["我", "晕", "倒", "了"] },
    { chinese: "我吃药了吗", pinyin: "wǒ chī yào le ma", russian: "Я принял лекарство?", level: 3, words: ["我", "吃", "药", "了", "吗"] },
    { chinese: "多喝热水", pinyin: "duō hē rè shuǐ", russian: "Пей больше горячей воды", level: 3, words: ["多", "喝", "热", "水"] },
    { chinese: "多休息", pinyin: "duō xiūxi", russian: "Больше отдыхай", level: 3, words: ["多", "休", "息"] },
    { chinese: "早日康复", pinyin: "zǎorì kāngfù", russian: "Выздоравливай скорее", level: 3, words: ["早", "日", "康", "复"] },
    { chinese: "我去药店", pinyin: "wǒ qù yàodiàn", russian: "Я иду в аптеку", level: 3, words: ["我", "去", "药", "店"] },

    // ==================== УРОВЕНЬ 4 ⭐⭐⭐⭐: ПУТЕШЕСТВИЯ, ОБЩЕНИЕ, ПОГОДА (120 фраз) ====================
    // --- Путешествия (30) ---
    { chinese: "我想去中国旅游", pinyin: "wǒ xiǎng qù Zhōngguó lǚyóu", russian: "Хочу поехать в Китай", level: 4, words: ["我", "想", "去", "中", "国", "旅", "游"] },
    { chinese: "护照在哪里", pinyin: "hùzhào zài nǎlǐ", russian: "Где паспорт?", level: 4, words: ["护", "照", "在", "哪", "里"] },
    { chinese: "我需要签证", pinyin: "wǒ xūyào qiānzhèng", russian: "Мне нужна виза", level: 4, words: ["我", "需", "要", "签", "证"] },
    { chinese: "在哪里取行李", pinyin: "zài nǎlǐ qǔ xíngli", russian: "Где получать багаж?", level: 4, words: ["在", "哪", "里", "取", "行", "李"] },
    { chinese: "我的行李丢了", pinyin: "wǒ de xíngli diū le", russian: "Мой багаж потерялся", level: 4, words: ["我", "的", "行", "李", "丢", "了"] },
    { chinese: "登机口在哪儿", pinyin: "dēngjī kǒu zài nǎr", russian: "Где выход на посадку?", level: 4, words: ["登", "机", "口", "在", "哪", "儿"] },
    { chinese: "飞机晚点了", pinyin: "fēijī wǎndiǎn le", russian: "Самолёт задерживается", level: 4, words: ["飞", "机", "晚", "点", "了"] },
    { chinese: "我要转机", pinyin: "wǒ yào zhuǎnjī", russian: "Мне нужна пересадка", level: 4, words: ["我", "要", "转", "机"] },
    { chinese: "靠窗的座位", pinyin: "kào chuāng de zuòwèi", russian: "Место у окна", level: 4, words: ["靠", "窗", "的", "座", "位"] },
    { chinese: "靠过道的座位", pinyin: "kào guòdào de zuòwèi", russian: "Место у прохода", level: 4, words: ["靠", "过", "道", "的", "座", "位"] },
    { chinese: "入境卡怎么填", pinyin: "rùjìng kǎ zěnme tián", russian: "Как заполнить карточку въезда?", level: 4, words: ["入", "境", "卡", "怎", "么", "填"] },
    { chinese: "海关在哪里", pinyin: "hǎiguān zài nǎlǐ", russian: "Где таможня?", level: 4, words: ["海", "关", "在", "哪", "里"] },
    { chinese: "我要申报物品", pinyin: "wǒ yào shēnbào wùpǐn", russian: "Мне нужно декларировать вещи", level: 4, words: ["我", "要", "申", "报", "物", "品"] },
    { chinese: "有什么要申报的吗", pinyin: "yǒu shénme yào shēnbào de ma", russian: "Есть что декларировать?", level: 4, words: ["有", "什", "么", "要", "申", "报", "的", "吗"] },
    { chinese: "这个城市很漂亮", pinyin: "zhè ge chéngshì hěn piàoliang", russian: "Этот город очень красивый", level: 4, words: ["这", "个", "城", "市", "很", "漂", "亮"] },
    { chinese: "有什么好玩的地方", pinyin: "yǒu shénme hǎowán de dìfang", russian: "Какие есть интересные места?", level: 4, words: ["有", "什", "么", "好", "玩", "的", "地", "方"] },
    { chinese: "请给我一张地图", pinyin: "qǐng gěi wǒ yì zhāng dìtú", russian: "Дайте карту, пожалуйста", level: 4, words: ["请", "给", "我", "一", "张", "地", "图"] },
    { chinese: "门票多少钱", pinyin: "ménpiào duōshao qián", russian: "Сколько стоит входной билет?", level: 4, words: ["门", "票", "多", "少", "钱"] },
    { chinese: "可以拍照吗", pinyin: "kěyǐ pāizhào ma", russian: "Можно фотографировать?", level: 4, words: ["可", "以", "拍", "照", "吗"] },
    { chinese: "可以帮我拍照吗", pinyin: "kěyǐ bāng wǒ pāizhào ma", russian: "Можете меня сфоткать?", level: 4, words: ["可", "以", "帮", "我", "拍", "照", "吗"] },
    { chinese: "这里可以吸烟吗", pinyin: "zhèlǐ kěyǐ xīyān ma", russian: "Здесь можно курить?", level: 4, words: ["这", "里", "可", "以", "吸", "烟", "吗"] },
    { chinese: "禁止吸烟", pinyin: "jìnzhǐ xīyān", russian: "Курить запрещено", level: 4, words: ["禁", "止", "吸", "烟"] },
    { chinese: "我来自俄罗斯", pinyin: "wǒ láizì Éluósī", russian: "Я из России", level: 4, words: ["我", "来", "自", "俄", "罗", "斯"] },
    { chinese: "我是来旅游的", pinyin: "wǒ shì lái lǚyóu de", russian: "Я приехал как турист", level: 4, words: ["我", "是", "来", "旅", "游", "的"] },
    { chinese: "我要兑换货币", pinyin: "wǒ yào duìhuàn huòbì", russian: "Мне нужно обменять валюту", level: 4, words: ["我", "要", "兑", "换", "货", "币"] },
    { chinese: "汇率是多少", pinyin: "huìlǜ shì duōshao", russian: "Какой курс?", level: 4, words: ["汇", "率", "是", "多", "少"] },
    { chinese: "附近有取款机吗", pinyin: "fùjìn yǒu qǔkuǎn jī ma", russian: "Рядом есть банкомат?", level: 4, words: ["附", "近", "有", "取", "款", "机", "吗"] },
    { chinese: "旅游旺季是什么时候", pinyin: "lǚyóu wàngjì shì shénme shíhou", russian: "Когда туристический сезон?", level: 4, words: ["旅", "游", "旺", "季", "是", "什", "么", "时", "候"] },
    { chinese: "我想买纪念品", pinyin: "wǒ xiǎng mǎi jìniànpǐn", russian: "Хочу купить сувениры", level: 4, words: ["我", "想", "买", "纪", "念", "品"] },
    { chinese: "哪里可以寄存行李", pinyin: "nǎlǐ kěyǐ jìcún xíngli", russian: "Где можно оставить багаж?", level: 4, words: ["哪", "里", "可", "以", "寄", "存", "行", "李"] },

    // --- Общение и телефон (30) ---
    { chinese: "你的电话号码是多少", pinyin: "nǐ de diànhuà hàomǎ shì duōshao", russian: "Какой твой номер?", level: 4, words: ["你", "的", "电", "话", "号", "码", "是", "多", "少"] },
    { chinese: "我可以加你微信吗", pinyin: "wǒ kěyǐ jiā nǐ Wēixìn ma", russian: "Можно добавить тебя в WeChat?", level: 4, words: ["我", "可", "以", "加", "你", "微", "信", "吗"] },
    { chinese: "扫一扫", pinyin: "sǎo yì sǎo", russian: "Сканируй (QR-код)", level: 4, words: ["扫", "一", "扫"] },
    { chinese: "我扫你还是你扫我", pinyin: "wǒ sǎo nǐ háishì nǐ sǎo wǒ", russian: "Я сканирую тебя или ты меня?", level: 4, words: ["我", "扫", "你", "还", "是", "你", "扫", "我"] },
    { chinese: "你微信号是多少", pinyin: "nǐ Wēixìn hào shì duōshao", russian: "Какой твой WeChat ID?", level: 4, words: ["你", "微", "信", "号", "是", "多", "少"] },
    { chinese: "我手机没电了", pinyin: "wǒ shǒujī méi diàn le", russian: "У меня телефон разрядился", level: 4, words: ["我", "手", "机", "没", "电", "了"] },
    { chinese: "有充电宝吗", pinyin: "yǒu chōngdiàn bǎo ma", russian: "Есть powerbank?", level: 4, words: ["有", "充", "电", "宝", "吗"] },
    { chinese: "能借我充电器吗", pinyin: "néng jiè wǒ chōngdiàn qì ma", russian: "Можешь одолжить зарядку?", level: 4, words: ["能", "借", "我", "充", "电", "器", "吗"] },
    { chinese: "信号不好", pinyin: "xìnhào bù hǎo", russian: "Сигнал плохой", level: 4, words: ["信", "号", "不", "好"] },
    { chinese: "请发短信给我", pinyin: "qǐng fā duǎnxìn gěi wǒ", russian: "Напиши мне SMS", level: 4, words: ["请", "发", "短", "信", "给", "我"] },
    { chinese: "我一会儿打给你", pinyin: "wǒ yíhuìr dǎ gěi nǐ", russian: "Я скоро позвоню", level: 4, words: ["我", "一", "会", "儿", "打", "给", "你"] },
    { chinese: "我们保持联系", pinyin: "wǒmen bǎochí liánxì", russian: "Будем на связи", level: 4, words: ["我", "们", "保", "持", "联", "系"] },
    { chinese: "我错过了你的电话", pinyin: "wǒ cuòguò le nǐ de diànhuà", russian: "Я пропустил твой звонок", level: 4, words: ["我", "错", "过", "了", "你", "的", "电", "话"] },
    { chinese: "占线", pinyin: "zhàn xiàn", russian: "Линия занята", level: 4, words: ["占", "线"] },
    { chinese: "我听不清", pinyin: "wǒ tīng bu qīng", russian: "Я плохо слышу", level: 4, words: ["我", "听", "不", "清"] },
    { chinese: "请大声一点", pinyin: "qǐng dàshēng yìdiǎn", russian: "Погромче, пожалуйста", level: 4, words: ["请", "大", "声", "一", "点"] },
    { chinese: "你什么时候有空", pinyin: "nǐ shénme shíhou yǒu kòng", russian: "Когда ты свободен?", level: 4, words: ["你", "什", "么", "时", "候", "有", "空"] },
    { chinese: "我们见面吧", pinyin: "wǒmen jiànmiàn ba", russian: "Давай встретимся", level: 4, words: ["我", "们", "见", "面", "吧"] },
    { chinese: "在哪里见面", pinyin: "zài nǎlǐ jiànmiàn", russian: "Где встретимся?", level: 4, words: ["在", "哪", "里", "见", "面"] },
    { chinese: "几点见面", pinyin: "jǐ diǎn jiànmiàn", russian: "Во сколько встреча?", level: 4, words: ["几", "点", "见", "面"] },
    { chinese: "我等你", pinyin: "wǒ děng nǐ", russian: "Я подожду тебя", level: 4, words: ["我", "等", "你"] },
    { chinese: "别迟到", pinyin: "bié chídào", russian: "Не опаздывай", level: 4, words: ["别", "迟", "到"] },
    { chinese: "我快到了", pinyin: "wǒ kuài dào le", russian: "Я почти на месте", level: 4, words: ["我", "快", "到", "了"] },
    { chinese: "我已经到了", pinyin: "wǒ yǐjīng dào le", russian: "Я уже пришёл", level: 4, words: ["我", "已", "经", "到", "了"] },
    { chinese: "你在哪儿", pinyin: "nǐ zài nǎr", russian: "Ты где?", level: 4, words: ["你", "在", "哪", "儿"] },
    { chinese: "我一会就到", pinyin: "wǒ yíhuì jiù dào", russian: "Скоро буду", level: 4, words: ["我", "一", "会", "就", "到"] },
    { chinese: "对不起我迟到了", pinyin: "duìbuqǐ wǒ chídào le", russian: "Извини, я опоздал", level: 4, words: ["对", "不", "起", "我", "迟", "到", "了"] },
    { chinese: "没关系", pinyin: "méi guānxi", russian: "Ничего страшного", level: 4, words: ["没", "关", "系"] },
    { chinese: "我请你吃饭", pinyin: "wǒ qǐng nǐ chīfàn", russian: "Я угощаю тебя обедом", level: 4, words: ["我", "请", "你", "吃", "饭"] },
    { chinese: "下次吧", pinyin: "xià cì ba", russian: "В следующий раз", level: 4, words: ["下", "次", "吧"] },

    // --- Погода и природа (30) ---
    { chinese: "今天天气怎么样", pinyin: "jīntiān tiānqì zěnmeyàng", russian: "Какая сегодня погода?", level: 4, words: ["今", "天", "天", "气", "怎", "么", "样"] },
    { chinese: "天气很好", pinyin: "tiānqì hěn hǎo", russian: "Погода хорошая", level: 4, words: ["天", "气", "很", "好"] },
    { chinese: "天气真糟糕", pinyin: "tiānqì zhēn zāogāo", russian: "Погода ужасная", level: 4, words: ["天", "气", "真", "糟", "糕"] },
    { chinese: "今天很热", pinyin: "jīntiān hěn rè", russian: "Сегодня жарко", level: 4, words: ["今", "天", "很", "热"] },
    { chinese: "今天很冷", pinyin: "jīntiān hěn lěng", russian: "Сегодня холодно", level: 4, words: ["今", "天", "很", "冷"] },
    { chinese: "下雨了", pinyin: "xià yǔ le", russian: "Пошёл дождь", level: 4, words: ["下", "雨", "了"] },
    { chinese: "下雪了", pinyin: "xià xuě le", russian: "Пошёл снег", level: 4, words: ["下", "雪", "了"] },
    { chinese: "刮风了", pinyin: "guā fēng le", russian: "Подул ветер", level: 4, words: ["刮", "风", "了"] },
    { chinese: "天晴了", pinyin: "tiān qíng le", russian: "Прояснилось", level: 4, words: ["天", "晴", "了"] },
    { chinese: "出太阳了", pinyin: "chū tàiyáng le", russian: "Солнце вышло", level: 4, words: ["出", "太", "阳", "了"] },
    { chinese: "天气预报说明天有雨", pinyin: "tiānqì yùbào shuō míngtiān yǒu yǔ", russian: "По прогнозу завтра дождь", level: 4, words: ["天", "气", "预", "报", "说", "明", "天", "有", "雨"] },
    { chinese: "今天多少度", pinyin: "jīntiān duōshao dù", russian: "Сколько градусов сегодня?", level: 4, words: ["今", "天", "多", "少", "度"] },
    { chinese: "零下十度", pinyin: "líng xià shí dù", russian: "Минус 10 градусов", level: 4, words: ["零", "下", "十", "度"] },
    { chinese: "湿度很大", pinyin: "shīdù hěn dà", russian: "Очень влажно", level: 4, words: ["湿", "度", "很", "大"] },
    { chinese: "要下雨了", pinyin: "yào xià yǔ le", russian: "Скоро пойдёт дождь", level: 4, words: ["要", "下", "雨", "了"] },
    { chinese: "带伞了吗", pinyin: "dài sǎn le ma", russian: "Ты взял зонт?", level: 4, words: ["带", "伞", "了", "吗"] },
    { chinese: "我淋湿了", pinyin: "wǒ lín shī le", russian: "Я промок", level: 4, words: ["我", "淋", "湿", "了"] },
    { chinese: "秋天很舒服", pinyin: "qiūtiān hěn shūfu", russian: "Осенью очень комфортно", level: 4, words: ["秋", "天", "很", "舒", "服"] },
    { chinese: "春天来了", pinyin: "chūntiān lái le", russian: "Весна пришла", level: 4, words: ["春", "天", "来", "了"] },
    { chinese: "我喜欢夏天", pinyin: "wǒ xǐhuan xiàtiān", russian: "Я люблю лето", level: 4, words: ["我", "喜", "欢", "夏", "天"] },
    { chinese: "冬天太冷了", pinyin: "dōngtiān tài lěng le", russian: "Зимой слишком холодно", level: 4, words: ["冬", "天", "太", "冷", "了"] },
    { chinese: "要下暴雨了", pinyin: "yào xià bàoyǔ le", russian: "Будет ливень", level: 4, words: ["要", "下", "暴", "雨", "了"] },
    { chinese: "打雷了", pinyin: "dǎ léi le", russian: "Гром гремит", level: 4, words: ["打", "雷", "了"] },
    { chinese: "有彩虹", pinyin: "yǒu cǎihóng", russian: "Радуга", level: 4, words: ["有", "彩", "虹"] },
    { chinese: "雾很大", pinyin: "wù hěn dà", russian: "Сильный туман", level: 4, words: ["雾", "很", "大"] },
    { chinese: "空气质量不好", pinyin: "kōngqì zhìliàng bù hǎo", russian: "Качество воздуха плохое", level: 4, words: ["空", "气", "质", "量", "不", "好"] },
    { chinese: "今天有雾霾", pinyin: "jīntiān yǒu wùmái", russian: "Сегодня смог", level: 4, words: ["今", "天", "有", "雾", "霾"] },
    { chinese: "月亮很圆", pinyin: "yuèliang hěn yuán", russian: "Луна круглая", level: 4, words: ["月", "亮", "很", "圆"] },
    { chinese: "星星很多", pinyin: "xīngxing hěn duō", russian: "Много звёзд", level: 4, words: ["星", "星", "很", "多"] },
    { chinese: "今天很闷热", pinyin: "jīntiān hěn mēnrè", russian: "Сегодня душно", level: 4, words: ["今", "天", "很", "闷", "热"] },

    // --- Развлечения и досуг (30) ---
    { chinese: "我们去看电影吧", pinyin: "wǒmen qù kàn diànyǐng ba", russian: "Пойдём в кино", level: 4, words: ["我", "们", "去", "看", "电", "影", "吧"] },
    { chinese: "你喜欢看什么电影", pinyin: "nǐ xǐhuan kàn shénme diànyǐng", russian: "Какие фильмы ты любишь?", level: 4, words: ["你", "喜", "欢", "看", "什", "么", "电", "影"] },
    { chinese: "这部电影很好看", pinyin: "zhè bù diànyǐng hěn hǎokàn", russian: "Этот фильм очень интересный", level: 4, words: ["这", "部", "电", "影", "很", "好", "看"] },
    { chinese: "有中文字幕吗", pinyin: "yǒu zhōngwén zìmù ma", russian: "Есть китайские субтитры?", level: 4, words: ["有", "中", "文", "字", "幕", "吗"] },
    { chinese: "太感动了", pinyin: "tài gǎndòng le", russian: "Очень трогательно", level: 4, words: ["太", "感", "动", "了"] },
    { chinese: "结局很意外", pinyin: "jiéjú hěn yìwài", russian: "Концовка неожиданная", level: 4, words: ["结", "局", "很", "意", "外"] },
    { chinese: "我们去唱歌吧", pinyin: "wǒmen qù chànggē ba", russian: "Пойдём в караоке", level: 4, words: ["我", "们", "去", "唱", "歌", "吧"] },
    { chinese: "你唱得很好听", pinyin: "nǐ chàng de hěn hǎotīng", russian: "Ты красиво поёшь", level: 4, words: ["你", "唱", "得", "很", "好", "听"] },
    { chinese: "你喜欢音乐吗", pinyin: "nǐ xǐhuan yīnyuè ma", russian: "Ты любишь музыку?", level: 4, words: ["你", "喜", "欢", "音", "乐", "吗"] },
    { chinese: "你会弹吉他吗", pinyin: "nǐ huì tán jítā ma", russian: "Ты умеешь играть на гитаре?", level: 4, words: ["你", "会", "弹", "吉", "他", "吗"] },
    { chinese: "我们去逛逛吧", pinyin: "wǒmen qù guàng guàng ba", russian: "Пойдём прогуляемся", level: 4, words: ["我", "们", "去", "逛", "逛", "吧"] },
    { chinese: "你喜欢运动吗", pinyin: "nǐ xǐhuan yùndòng ma", russian: "Ты любишь спорт?", level: 4, words: ["你", "喜", "欢", "运", "动", "吗"] },
    { chinese: "我去健身房", pinyin: "wǒ qù jiànshēnfáng", russian: "Я иду в спортзал", level: 4, words: ["我", "去", "健", "身", "房"] },
    { chinese: "你喜欢旅游吗", pinyin: "nǐ xǐhuan lǚyóu ma", russian: "Ты любишь путешествовать?", level: 4, words: ["你", "喜", "欢", "旅", "游", "吗"] },
    { chinese: "我周末去打篮球", pinyin: "wǒ zhōumò qù dǎ lánqiú", russian: "В выходные играю в баскетбол", level: 4, words: ["我", "周", "末", "去", "打", "篮", "球"] },
    { chinese: "我喜欢看小说", pinyin: "wǒ xǐhuan kàn xiǎoshuō", russian: "Я люблю читать романы", level: 4, words: ["我", "喜", "欢", "看", "小", "说"] },
    { chinese: "你很幽默", pinyin: "nǐ hěn yōumò", russian: "Ты очень смешной", level: 4, words: ["你", "很", "幽", "默"] },
    { chinese: "开玩笑的", pinyin: "kāi wánxiào de", russian: "Я шучу", level: 4, words: ["开", "玩", "笑", "的"] },
    { chinese: "别当真", pinyin: "bié dàngzhēn", russian: "Не принимай всерьёз", level: 4, words: ["别", "当", "真"] },
    { chinese: "你真厉害", pinyin: "nǐ zhēn lìhai", russian: "Ты крутой!", level: 4, words: ["你", "真", "厉", "害"] },
    { chinese: "加油", pinyin: "jiā yóu", russian: "Давай! Вперёд!", level: 4, words: ["加", "油"] },
    { chinese: "放心吧", pinyin: "fàng xīn ba", russian: "Не волнуйся", level: 4, words: ["放", "心", "吧"] },
    { chinese: "我也是这么想的", pinyin: "wǒ yě shì zhème xiǎng de", russian: "Я тоже так думаю", level: 4, words: ["我", "也", "是", "这", "么", "想", "的"] },
    { chinese: "我不这么认为", pinyin: "wǒ bù zhème rènwéi", russian: "Я так не считаю", level: 4, words: ["我", "不", "这", "么", "认", "为"] },
    { chinese: "听说你升职了", pinyin: "tīngshuō nǐ shēngzhí le", russian: "Слышал, тебя повысили", level: 4, words: ["听", "说", "你", "升", "职", "了"] },
    { chinese: "真的假的", pinyin: "zhēn de jiǎ de", russian: "Правда или нет?", level: 4, words: ["真", "的", "假", "的"] },
    { chinese: "真没想到", pinyin: "zhēn méi xiǎng dào", russian: "Не ожидал", level: 4, words: ["真", "没", "想", "到"] },
    { chinese: "太可惜了", pinyin: "tài kěxī le", russian: "Очень жаль", level: 4, words: ["太", "可", "惜", "了"] },
    { chinese: "没事别担心", pinyin: "méi shì bié dānxīn", russian: "Всё в порядке, не переживай", level: 4, words: ["没", "事", "别", "担", "心"] },
    { chinese: "一切都会好起来的", pinyin: "yíqiè dōu huì hǎo qǐlái de", russian: "Всё наладится", level: 4, words: ["一", "切", "都", "会", "好", "起", "来", "的"] }
];
// ==================== УРОВЕНЬ 5 ⭐⭐⭐⭐⭐: БИЗНЕС, ЭМОЦИИ, ПРАКТИКА (120 фраз) ====================
    // --- Бизнес и переговоры (30) ---
    { chinese: "很高兴和你见面", pinyin: "hěn gāoxìng hé nǐ jiànmiàn", russian: "Рад встрече с вами", level: 5, words: ["很", "高", "兴", "和", "你", "见", "面"] },
    { chinese: "这是我的名片", pinyin: "zhè shì wǒ de míngpiàn", russian: "Это моя визитка", level: 5, words: ["这", "是", "我", "的", "名", "片"] },
    { chinese: "请问您贵姓", pinyin: "qǐngwèn nín guìxìng", russian: "Как ваша фамилия?", level: 5, words: ["请", "问", "您", "贵", "姓"] },
    { chinese: "希望我们合作愉快", pinyin: "xīwàng wǒmen hézuò yúkuài", russian: "Надеюсь на приятное сотрудничество", level: 5, words: ["希", "望", "我", "们", "合", "作", "愉", "快"] },
    { chinese: "我们对这个项目很感兴趣", pinyin: "wǒmen duì zhè ge xiàngmù hěn gǎn xìngqù", russian: "Нам очень интересен этот проект", level: 5, words: ["我", "们", "对", "这", "个", "项", "目", "很", "感", "兴", "趣"] },
    { chinese: "价格还可以商量吗", pinyin: "jiàgé hái kěyǐ shāngliang ma", russian: "Цена ещё обсуждается?", level: 5, words: ["价", "格", "还", "可", "以", "商", "量", "吗"] },
    { chinese: "这是最低价了", pinyin: "zhè shì zuì dī jià le", russian: "Это минимальная цена", level: 5, words: ["这", "是", "最", "低", "价", "了"] },
    { chinese: "质量怎么样", pinyin: "zhìliàng zěnmeyàng", russian: "Как качество?", level: 5, words: ["质", "量", "怎", "么", "样"] },
    { chinese: "交货时间是什么时候", pinyin: "jiāo huò shíjiān shì shénme shíhou", russian: "Когда срок поставки?", level: 5, words: ["交", "货", "时", "间", "是", "什", "么", "时", "候"] },
    { chinese: "我们签合同吧", pinyin: "wǒmen qiān hétong ba", russian: "Давайте подпишем контракт", level: 5, words: ["我", "们", "签", "合", "同", "吧"] },
    { chinese: "请仔细阅读条款", pinyin: "qǐng zǐxì yuèdú tiáokuǎn", russian: "Внимательно прочитайте условия", level: 5, words: ["请", "仔", "细", "阅", "读", "条", "款"] },
    { chinese: "如果有问题请随时联系我", pinyin: "rúguǒ yǒu wèntí qǐng suíshí liánxì wǒ", russian: "Если будут вопросы, свяжитесь со мной", level: 5, words: ["如", "果", "有", "问", "题", "请", "随", "时", "联", "系", "我"] },
    { chinese: "预付款是多少", pinyin: "yùfù kuǎn shì duōshao", russian: "Какой аванс?", level: 5, words: ["预", "付", "款", "是", "多", "少"] },
    { chinese: "我们会按时完成", pinyin: "wǒmen huì ànshí wánchéng", russian: "Мы выполним в срок", level: 5, words: ["我", "们", "会", "按", "时", "完", "成"] },
    { chinese: "有什么风险吗", pinyin: "yǒu shénme fēngxiǎn ma", russian: "Какие есть риски?", level: 5, words: ["有", "什", "么", "风", "险", "吗"] },
    { chinese: "我们需要更多时间", pinyin: "wǒmen xūyào gèng duō shíjiān", russian: "Нам нужно больше времени", level: 5, words: ["我", "们", "需", "要", "更", "多", "时", "间"] },
    { chinese: "可以延长截止日期吗", pinyin: "kěyǐ yáncháng jiézhǐ rìqī ma", russian: "Можно продлить дедлайн?", level: 5, words: ["可", "以", "延", "长", "截", "止", "日", "期", "吗"] },
    { chinese: "我不同意这个方案", pinyin: "wǒ bù tóngyì zhè ge fāng'àn", russian: "Я не согласен с этим планом", level: 5, words: ["我", "不", "同", "意", "这", "个", "方", "案"] },
    { chinese: "我们再讨论一下吧", pinyin: "wǒmen zài tǎolùn yíxià ba", russian: "Давайте ещё обсудим", level: 5, words: ["我", "们", "再", "讨", "论", "一", "下", "吧"] },
    { chinese: "这是我们的建议", pinyin: "zhè shì wǒmen de jiànyì", russian: "Это наше предложение", level: 5, words: ["这", "是", "我", "们", "的", "建", "议"] },
    { chinese: "你方有什么要求", pinyin: "nǐ fāng yǒu shénme yāoqiú", russian: "Какие у вас требования?", level: 5, words: ["你", "方", "有", "什", "么", "要", "求"] },
    { chinese: "我们可以提供折扣", pinyin: "wǒmen kěyǐ tígōng zhékòu", russian: "Мы можем предоставить скидку", level: 5, words: ["我", "们", "可", "以", "提", "供", "折", "扣"] },
    { chinese: "这是最终报价", pinyin: "zhè shì zuìzhōng bàojià", russian: "Это окончательное предложение", level: 5, words: ["这", "是", "最", "终", "报", "价"] },
    { chinese: "祝我们合作成功", pinyin: "zhù wǒmen hézuò chénggōng", russian: "За успешное сотрудничество", level: 5, words: ["祝", "我", "们", "合", "作", "成", "功"] },
    { chinese: "我会尽快回复你", pinyin: "wǒ huì jǐnkuài huífù nǐ", russian: "Я отвечу как можно скорее", level: 5, words: ["我", "会", "尽", "快", "回", "复", "你"] },
    { chinese: "请保持联系", pinyin: "qǐng bǎochí liánxì", russian: "Будьте на связи", level: 5, words: ["请", "保", "持", "联", "系"] },
    { chinese: "我期待您的回复", pinyin: "wǒ qīdài nín de huífù", russian: "Жду вашего ответа", level: 5, words: ["我", "期", "待", "您", "的", "回", "复"] },
    { chinese: "谢谢您的宝贵时间", pinyin: "xièxie nín de bǎoguì shíjiān", russian: "Спасибо за ваше драгоценное время", level: 5, words: ["谢", "谢", "您", "的", "宝", "贵", "时", "间"] },
    { chinese: "我们会考虑你的建议", pinyin: "wǒmen huì kǎolǜ nǐ de jiànyì", russian: "Мы рассмотрим ваше предложение", level: 5, words: ["我", "们", "会", "考", "虑", "你", "的", "建", "议"] },
    { chinese: "请给我发邮件确认", pinyin: "qǐng gěi wǒ fā yóujiàn quèrèn", russian: "Пришлите подтверждение по почте", level: 5, words: ["请", "给", "我", "发", "邮", "件", "确", "认"] },

    // --- Эмоции и чувства (30) ---
    { chinese: "我很开心", pinyin: "wǒ hěn kāixīn", russian: "Я очень рад", level: 5, words: ["我", "很", "开", "心"] },
    { chinese: "我太兴奋了", pinyin: "wǒ tài xīngfèn le", russian: "Я в восторге!", level: 5, words: ["我", "太", "兴", "奋", "了"] },
    { chinese: "我很难过", pinyin: "wǒ hěn nánguò", russian: "Мне очень грустно", level: 5, words: ["我", "很", "难", "过"] },
    { chinese: "我很生气", pinyin: "wǒ hěn shēngqì", russian: "Я очень зол", level: 5, words: ["我", "很", "生", "气"] },
    { chinese: "我非常失望", pinyin: "wǒ fēicháng shīwàng", russian: "Я очень разочарован", level: 5, words: ["我", "非", "常", "失", "望"] },
    { chinese: "我很担心", pinyin: "wǒ hěn dānxīn", russian: "Я очень волнуюсь", level: 5, words: ["我", "很", "担", "心"] },
    { chinese: "我紧张得要命", pinyin: "wǒ jǐnzhāng de yàomìng", russian: "Я жутко нервничаю", level: 5, words: ["我", "紧", "张", "得", "要", "命"] },
    { chinese: "我很感动", pinyin: "wǒ hěn gǎndòng", russian: "Я очень тронут", level: 5, words: ["我", "很", "感", "动"] },
    { chinese: "我真受不了了", pinyin: "wǒ zhēn shòu bù liǎo le", russian: "Я больше не выдержу", level: 5, words: ["我", "真", "受", "不", "了", "了"] },
    { chinese: "我松了一口气", pinyin: "wǒ sōng le yì kǒu qì", russian: "У меня гора с плеч", level: 5, words: ["我", "松", "了", "一", "口", "气"] },
    { chinese: "我感到很意外", pinyin: "wǒ gǎndào hěn yìwài", russian: "Я очень удивлён", level: 5, words: ["我", "感", "到", "很", "意", "外"] },
    { chinese: "我很满足", pinyin: "wǒ hěn mǎnzú", russian: "Я доволен", level: 5, words: ["我", "很", "满", "足"] },
    { chinese: "我觉得很无聊", pinyin: "wǒ juéde hěn wúliáo", russian: "Мне скучно", level: 5, words: ["我", "觉", "得", "很", "无", "聊"] },
    { chinese: "我很羡慕你", pinyin: "wǒ hěn xiànmù nǐ", russian: "Я тебе завидую", level: 5, words: ["我", "很", "羡", "慕", "你"] },
    { chinese: "我为你骄傲", pinyin: "wǒ wèi nǐ jiāo'ào", russian: "Я горжусь тобой", level: 5, words: ["我", "为", "你", "骄", "傲"] },
    { chinese: "我很尴尬", pinyin: "wǒ hěn gāngà", russian: "Мне неловко", level: 5, words: ["我", "很", "尴", "尬"] },
    { chinese: "我太后悔了", pinyin: "wǒ tài hòuhuǐ le", russian: "Я очень жалею", level: 5, words: ["我", "太", "后", "悔", "了"] },
    { chinese: "我很害羞", pinyin: "wǒ hěn hàixiū", russian: "Я стесняюсь", level: 5, words: ["我", "很", "害", "羞"] },
    { chinese: "我好想你", pinyin: "wǒ hǎo xiǎng nǐ", russian: "Я очень скучаю по тебе", level: 5, words: ["我", "好", "想", "你"] },
    { chinese: "我爱你", pinyin: "wǒ ài nǐ", russian: "Я тебя люблю", level: 5, words: ["我", "爱", "你"] },
    { chinese: "我讨厌这样", pinyin: "wǒ tǎoyàn zhèyàng", russian: "Мне это не нравится", level: 5, words: ["我", "讨", "厌", "这", "样"] },
    { chinese: "我很感激你", pinyin: "wǒ hěn gǎnjī nǐ", russian: "Я тебе очень благодарен", level: 5, words: ["我", "很", "感", "激", "你"] },
    { chinese: "我不在乎", pinyin: "wǒ bú zàihu", russian: "Мне всё равно", level: 5, words: ["我", "不", "在", "乎"] },
    { chinese: "我吓坏了", pinyin: "wǒ xià huài le", russian: "Я в ужасе", level: 5, words: ["我", "吓", "坏", "了"] },
    { chinese: "你让我很开心", pinyin: "nǐ ràng wǒ hěn kāixīn", russian: "Ты меня очень радуешь", level: 5, words: ["你", "让", "我", "很", "开", "心"] },
    { chinese: "真让人沮丧", pinyin: "zhēn ràng rén jǔsàng", russian: "Это так расстраивает", level: 5, words: ["真", "让", "人", "沮", "丧"] },
    { chinese: "我心里很乱", pinyin: "wǒ xīnli hěn luàn", russian: "У меня в душе chaos", level: 5, words: ["我", "心", "里", "很", "乱"] },
    { chinese: "我受够了", pinyin: "wǒ shòu gòu le", russian: "С меня хватит", level: 5, words: ["我", "受", "够", "了"] },
    { chinese: "我很好，谢谢", pinyin: "wǒ hěn hǎo, xièxie", russian: "У меня всё хорошо, спасибо", level: 5, words: ["我", "很", "好", "谢", "谢"] },
    { chinese: "别难过了", pinyin: "bié nánguò le", russian: "Не грусти", level: 5, words: ["别", "难", "过", "了"] },

    // --- Проблемы и их решение (30) ---
    { chinese: "我的钱包丢了", pinyin: "wǒ de qiánbāo diū le", russian: "Я потерял кошелёк", level: 5, words: ["我", "的", "钱", "包", "丢", "了"] },
    { chinese: "我错过飞机了", pinyin: "wǒ cuòguò fēijī le", russian: "Я опоздал на самолёт", level: 5, words: ["我", "错", "过", "飞", "机", "了"] },
    { chinese: "能帮我个忙吗", pinyin: "néng bāng wǒ ge máng ma", russian: "Можешь помочь?", level: 5, words: ["能", "帮", "我", "个", "忙", "吗"] },
    { chinese: "我不知道该怎么办", pinyin: "wǒ bù zhīdào gāi zěnme bàn", russian: "Не знаю, что делать", level: 5, words: ["我", "不", "知", "道", "该", "怎", "么", "办"] },
    { chinese: "我遇到麻烦了", pinyin: "wǒ yùdào máfan le", russian: "У меня проблемы", level: 5, words: ["我", "遇", "到", "麻", "烦", "了"] },
    { chinese: "请帮我报警", pinyin: "qǐng bāng wǒ bàojǐng", russian: "Вызовите полицию", level: 5, words: ["请", "帮", "我", "报", "警"] },
    { chinese: "有人偷了我的东西", pinyin: "yǒu rén tōu le wǒ de dōngxi", russian: "Кто-то украл мои вещи", level: 5, words: ["有", "人", "偷", "了", "我", "的", "东", "西"] },
    { chinese: "我要报失", pinyin: "wǒ yào bàoshī", russian: "Я хочу заявить о пропаже", level: 5, words: ["我", "要", "报", "失"] },
    { chinese: "我的钥匙忘在房间里了", pinyin: "wǒ de yàoshi wàng zài fángjiān lǐ le", russian: "Я забыл ключи в номере", level: 5, words: ["我", "的", "钥", "匙", "忘", "在", "房", "间", "里", "了"] },
    { chinese: "电梯坏了", pinyin: "diàntī huài le", russian: "Лифт сломался", level: 5, words: ["电", "梯", "坏", "了"] },
    { chinese: "停电了", pinyin: "tíng diàn le", russian: "Электричество отключили", level: 5, words: ["停", "电", "了"] },
    { chinese: "漏水了", pinyin: "lòu shuǐ le", russian: "Протечка воды", level: 5, words: ["漏", "水", "了"] },
    { chinese: "房间太吵了", pinyin: "fángjiān tài chǎo le", russian: "В номере слишком шумно", level: 5, words: ["房", "间", "太", "吵", "了"] },
    { chinese: "空调不工作了", pinyin: "kōngtiáo bù gōngzuò le", russian: "Кондиционер не работает", level: 5, words: ["空", "调", "不", "工", "作", "了"] },
    { chinese: "请叫维修工", pinyin: "qǐng jiào wéixiū gōng", russian: "Вызовите мастера", level: 5, words: ["请", "叫", "维", "修", "工"] },
    { chinese: "我预约了维修", pinyin: "wǒ yùyuē le wéixiū", russian: "Я записался на ремонт", level: 5, words: ["我", "预", "约", "了", "维", "修"] },
    { chinese: "可以换房间吗", pinyin: "kěyǐ huàn fángjiān ma", russian: "Можно поменять номер?", level: 5, words: ["可", "以", "换", "房", "间", "吗"] },
    { chinese: "我要投诉", pinyin: "wǒ yào tóusù", russian: "Я хочу пожаловаться", level: 5, words: ["我", "要", "投", "诉"] },
    { chinese: "我对服务不满意", pinyin: "wǒ duì fúwù bù mǎnyì", russian: "Я недоволен обслуживанием", level: 5, words: ["我", "对", "服", "务", "不", "满", "意"] },
    { chinese: "能退款吗", pinyin: "néng tuì kuǎn ma", russian: "Можно вернуть деньги?", level: 5, words: ["能", "退", "款", "吗"] },
    { chinese: "这不合理", pinyin: "zhè bù hélǐ", russian: "Это несправедливо", level: 5, words: ["这", "不", "合", "理"] },
    { chinese: "我要求见经理", pinyin: "wǒ yāoqiú jiàn jīnglǐ", russian: "Я требую менеджера", level: 5, words: ["我", "要", "求", "见", "经", "理"] },
    { chinese: "这个坏了，能换一个吗", pinyin: "zhè ge huài le, néng huàn yí ge ma", russian: "Это сломано, можно заменить?", level: 5, words: ["这", "个", "坏", "了", "能", "换", "一", "个", "吗"] },
    { chinese: "这不是我点的", pinyin: "zhè bú shì wǒ diǎn de", russian: "Это не то, что я заказывал", level: 5, words: ["这", "不", "是", "我", "点", "的"] },
    { chinese: "你误会了", pinyin: "nǐ wùhuì le", russian: "Ты неправильно понял", level: 5, words: ["你", "误", "会", "了"] },
    { chinese: "我道歉", pinyin: "wǒ dàoqiàn", russian: "Я приношу извинения", level: 5, words: ["我", "道", "歉"] },
    { chinese: "是我的错", pinyin: "shì wǒ de cuò", russian: "Это моя вина", level: 5, words: ["是", "我", "的", "错"] },
    { chinese: "我保证不再发生", pinyin: "wǒ bǎozhèng bú zài fāshēng", russian: "Обещаю, больше не повторится", level: 5, words: ["我", "保", "证", "不", "再", "发", "生"] },
    { chinese: "谢谢你的理解", pinyin: "xièxie nǐ de lǐjiě", russian: "Спасибо за понимание", level: 5, words: ["谢", "谢", "你", "的", "理", "解"] },
    { chinese: "问题解决了", pinyin: "wèntí jiějué le", russian: "Проблема решена", level: 5, words: ["问", "题", "解", "决", "了"] },

    // --- Планы и будущее (30) ---
    { chinese: "你明天有什么计划", pinyin: "nǐ míngtiān yǒu shénme jìhuà", russian: "Какие планы на завтра?", level: 5, words: ["你", "明", "天", "有", "什", "么", "计", "划"] },
    { chinese: "我想去学车", pinyin: "wǒ xiǎng qù xué chē", russian: "Хочу научиться водить", level: 5, words: ["我", "想", "去", "学", "车"] },
    { chinese: "我打算明年去中国", pinyin: "wǒ dǎsuàn míngnián qù Zhōngguó", russian: "Планирую поехать в Китай в следующем году", level: 5, words: ["我", "打", "算", "明", "年", "去", "中", "国"] },
    { chinese: "我希望有一天能说流利的中文", pinyin: "wǒ xīwàng yǒu yì tiān néng shuō liúlì de zhōngwén", russian: "Надеюсь однажды заговорить свободно по-китайски", level: 5, words: ["我", "希", "望", "有", "一", "天", "能", "说", "流", "利", "的", "中", "文"] },
    { chinese: "我想换工作", pinyin: "wǒ xiǎng huàn gōngzuò", russian: "Хочу сменить работу", level: 5, words: ["我", "想", "换", "工", "作"] },
    { chinese: "你有什么梦想", pinyin: "nǐ yǒu shénme mèngxiǎng", russian: "Какая у тебя мечта?", level: 5, words: ["你", "有", "什", "么", "梦", "想"] },
    { chinese: "我想开一家公司", pinyin: "wǒ xiǎng kāi yì jiā gōngsī", russian: "Хочу открыть компанию", level: 5, words: ["我", "想", "开", "一", "家", "公", "司"] },
    { chinese: "我计划明年结婚", pinyin: "wǒ jìhuà míngnián jiéhūn", russian: "Планирую жениться в следующем году", level: 5, words: ["我", "计", "划", "明", "年", "结", "婚"] },
    { chinese: "我们明年去旅行吧", pinyin: "wǒmen míngnián qù lǚxíng ba", russian: "Давай поедем путешествовать в следующем году", level: 5, words: ["我", "们", "明", "年", "去", "旅", "行", "吧"] },
    { chinese: "我想买房子", pinyin: "wǒ xiǎng mǎi fángzi", russian: "Хочу купить квартиру", level: 5, words: ["我", "想", "买", "房", "子"] },
    { chinese: "我还没决定", pinyin: "wǒ hái méi juédìng", russian: "Я ещё не решил", level: 5, words: ["我", "还", "没", "决", "定"] },
    { chinese: "让我考虑一下", pinyin: "ràng wǒ kǎolǜ yíxià", russian: "Дай мне подумать", level: 5, words: ["让", "我", "考", "虑", "一", "下"] },
    { chinese: "也许吧", pinyin: "yěxǔ ba", russian: "Может быть", level: 5, words: ["也", "许", "吧"] },
    { chinese: "有可能", pinyin: "yǒu kěnéng", russian: "Возможно", level: 5, words: ["有", "可", "能"] },
    { chinese: "很难说", pinyin: "hěn nán shuō", russian: "Трудно сказать", level: 5, words: ["很", "难", "说"] },
    { chinese: "到时候再说吧", pinyin: "dào shíhou zài shuō ba", russian: "Там видно будет", level: 5, words: ["到", "时", "候", "再", "说", "吧"] },
    { chinese: "船到桥头自然直", pinyin: "chuán dào qiáotóu zìrán zhí", russian: "Всё образуется", level: 5, words: ["船", "到", "桥", "头", "自", "然", "直"] },
    { chinese: "我希望如此", pinyin: "wǒ xīwàng rúcǐ", russian: "Надеюсь на это", level: 5, words: ["我", "希", "望", "如", "此"] },
    { chinese: "走着瞧吧", pinyin: "zǒu zhe qiáo ba", russian: "Поживём — увидим", level: 5, words: ["走", "着", "瞧", "吧"] },
    { chinese: "我对未来很乐观", pinyin: "wǒ duì wèilái hěn lèguān", russian: "Я оптимистичен насчёт будущего", level: 5, words: ["我", "对", "未", "来", "很", "乐", "观"] },
    { chinese: "重要的是过程", pinyin: "zhòngyào de shì guòchéng", russian: "Важен сам процесс", level: 5, words: ["重", "要", "的", "是", "过", "程"] },
    { chinese: "一步一步来", pinyin: "yí bù yí bù lái", russian: "Шаг за шагом", level: 5, words: ["一", "步", "一", "步", "来"] },
    { chinese: "慢慢来别急", pinyin: "màn man lái bié jí", russian: "Не спеши, постепенно", level: 5, words: ["慢", "慢", "来", "别", "急"] },
    { chinese: "我对自己的未来充满信心", pinyin: "wǒ duì zìjǐ de wèilái chōngmǎn xìnxīn", russian: "Я уверен в своём будущем", level: 5, words: ["我", "对", "自", "己", "的", "未", "来", "充", "满", "信", "心"] },
    { chinese: "祝你成功", pinyin: "zhù nǐ chénggōng", russian: "Желаю успеха", level: 5, words: ["祝", "你", "成", "功"] },
    { chinese: "一切都会好的", pinyin: "yíqiè dōu huì hǎo de", russian: "Всё будет хорошо", level: 5, words: ["一", "切", "都", "会", "好", "的"] },
    { chinese: "我会努力的", pinyin: "wǒ huì nǔlì de", russian: "Я буду стараться", level: 5, words: ["我", "会", "努", "力", "的"] },
    { chinese: "永不放弃", pinyin: "yǒng bù fàngqì", russian: "Никогда не сдавайся", level: 5, words: ["永", "不", "放", "弃"] },
    { chinese: "机会是留给有准备的人的", pinyin: "jīhuì shì liú gěi yǒu zhǔnbèi de rén de", russian: "Шанс даётся подготовленным", level: 5, words: ["机", "会", "是", "留", "给", "有", "准", "备", "的", "人", "的"] },
    { chinese: "千里之行始于足下", pinyin: "qiān lǐ zhī xíng shǐ yú zú xià", russian: "Дорога в тысячу ли начинается с первого шага", level: 5, words: ["千", "里", "之", "行", "始", "于", "足", "下"] }
];
